import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { Node, Edge } from '@xyflow/react'

interface PDFExportOptions {
  title: string
  description?: string
  author?: string
  nodes: Node[]
  edges: Edge[]
}

export function generatePDF(options: PDFExportOptions): jsPDF {
  const { title, description, author, nodes, edges } = options
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let y = margin

  // ─── Title Page ──────────────────────────────────────────────────────
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text(title, pageWidth / 2, 60, { align: 'center' })

  if (description) {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(description, pageWidth / 2, 75, { align: 'center', maxWidth: pageWidth - 2 * margin })
  }

  doc.setFontSize(11)
  doc.setTextColor(120, 120, 120)
  const metaLines = [
    `Generated: ${new Date().toLocaleDateString()}`,
    `Components: ${nodes.length}`,
    `Connections: ${edges.length}`,
    author ? `Author: ${author}` : '',
  ].filter(Boolean)
  doc.text(metaLines, pageWidth / 2, 100, { align: 'center' })

  doc.setDrawColor(200, 200, 200)
  doc.line(margin, 120, pageWidth - margin, 120)

  doc.setFontSize(10)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by JobStack • https://jobstack.app', pageWidth / 2, 280, { align: 'center' })

  // ─── Summary Page ────────────────────────────────────────────────────
  doc.addPage()
  y = margin

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('Architecture Summary', margin, y)
  y += 15

  // Component type distribution
  const typeCounts = new Map<string, number>()
  for (const node of nodes) {
    const type = (node.data as { label?: string })?.label || node.type || 'Unknown'
    const category = (node.data as { category?: string })?.category || 'other'
    const key = `${category}/${type}`
    typeCounts.set(key, (typeCounts.get(key) || 0) + 1)
  }

  const summaryData = Array.from(typeCounts.entries())
    .sort((a, b) => b[1] - a[1])
    .map(([key, count]) => {
      const [category, name] = key.split('/')
      return [name, category, String(count)]
    })

  autoTable(doc, {
    startY: y,
    head: [['Component', 'Category', 'Count']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] },
    margin: { left: margin, right: margin },
  })

  // @ts-expect-error jspdf-autotable extends jsPDF
  y = doc.lastAutoTable.finalY + 15

  // Provider distribution
  const providerCounts = new Map<string, number>()
  for (const node of nodes) {
    const provider = (node.data as { provider?: string })?.provider || 'unknown'
    providerCounts.set(provider, (providerCounts.get(provider) || 0) + 1)
  }

  if (providerCounts.size > 0) {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Provider Distribution', margin, y)
    y += 8

    autoTable(doc, {
      startY: y,
      head: [['Cloud Provider', 'Components']],
      body: Array.from(providerCounts.entries())
        .map(([provider, count]) => [provider.toUpperCase(), String(count)]),
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] },
      margin: { left: margin, right: margin },
    })

    // @ts-expect-error jspdf-autotable extends jsPDF
    y = doc.lastAutoTable.finalY + 15
  }

  // ─── Component Details Page ──────────────────────────────────────────
  doc.addPage()
  y = margin

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('Component Details', margin, y)
  y += 12

  const nodeMap = new Map(nodes.map(n => [n.id, n]))

  for (const node of nodes) {
    const label = (node.data as { label?: string })?.label || node.id
    const category = (node.data as { category?: string })?.category || ''
    const provider = (node.data as { provider?: string })?.provider || ''

    // Check if we need a new page
    if (y > 260) {
      doc.addPage()
      y = margin
    }

    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(37, 99, 235)
    doc.text(label, margin, y)
    y += 6

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(`Type: ${node.type || 'default'} | Category: ${category} | Provider: ${provider}`, margin, y)
    y += 5

    // Connections
    const incoming = edges.filter(e => e.target === node.id)
    const outgoing = edges.filter(e => e.source === node.id)

    if (incoming.length > 0 || outgoing.length > 0) {
      doc.setTextColor(60, 60, 60)
      const connLines: string[] = []
      for (const e of incoming) {
        const src = nodeMap.get(e.source)
        connLines.push(`← ${(src?.data as { label?: string })?.label || e.source}`)
      }
      for (const e of outgoing) {
        const tgt = nodeMap.get(e.target)
        connLines.push(`→ ${(tgt?.data as { label?: string })?.label || e.target}`)
      }
      doc.text(connLines.join('  |  '), margin + 2, y, { maxWidth: pageWidth - 2 * margin })
      y += 5 * Math.ceil(connLines.join('  |  ').length / 80)
    }

    y += 4
    doc.setDrawColor(230, 230, 230)
    doc.line(margin, y, pageWidth - margin, y)
    y += 6
  }

  // ─── Connections Table ───────────────────────────────────────────────
  if (edges.length > 0) {
    doc.addPage()
    y = margin

    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text('Connection Map', margin, y)
    y += 12

    const connectionData = edges.map(edge => {
      const source = nodeMap.get(edge.source)
      const target = nodeMap.get(edge.target)
      return [
        (source?.data as { label?: string })?.label || edge.source,
        (target?.data as { label?: string })?.label || edge.target,
        (edge.label as string) || '-',
      ]
    })

    autoTable(doc, {
      startY: y,
      head: [['Source', 'Target', 'Label']],
      body: connectionData,
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] },
      margin: { left: margin, right: margin },
    })
  }

  return doc
}

export function downloadPDF(options: PDFExportOptions) {
  const doc = generatePDF(options)
  const filename = `${options.title.replace(/[^a-zA-Z0-9]/g, '_')}_architecture.pdf`
  doc.save(filename)
}
