import {
  Code,
  Database,
  Server,
  Cloud,
  HardDrive,
  Globe,
  Lock,
  Mail,
  Network,
  Smartphone,
  Zap,
  Container,
  Box,
  Activity,
  BarChart,
  MessageSquare,
  Search,
  ShoppingCart,
  Users,
  Workflow,
  GitBranch,
  Shield,
  FileCode,
  Terminal,
  Cog,
  Radio,
  Wifi,
  Eye,
  Gauge,
  Key,
  Package,
  Building2,
  CreditCard,
} from 'lucide-react'

export type ComponentCategory =
  | 'frontend'
  | 'backend'
  | 'database'
  | 'cloud'
  | 'service'
  | 'devops'
  | 'security'
  | 'analytics'
  | 'networking'
  | 'compute'
  | 'storage'
  | 'identity'
  | 'containers'
  | 'ai'
  | 'monitoring'
export type CloudProvider = 'aws' | 'gcp' | 'azure' | 'cloudflare' | 'vercel' | 'generic'
export type ServiceType = 'iaas' | 'paas' | 'saas' | 'hosting' | 'generic'

/**
 * generatorType describes what kind of code/config this component produces during export:
 * - 'terraform'    → HCL resource block via Terraform (IaaS/PaaS on AWS/Azure/GCP)
 * - 'cicd'         → CI/CD YAML file (GitHub Actions, GitLab CI, Jenkins, etc.)
 * - 'kubernetes'   → Kubernetes manifest / Helm values (ArgoCD, Helm)
 * - 'docker'       → docker-compose service entry
 * - 'monitoring'   → observability config (Datadog agent, Prometheus scrape config)
 * - 'documentation'→ no code generated; component is an architectural annotation only
 */
export type GeneratorType =
  | 'terraform'
  | 'cicd'
  | 'kubernetes'
  | 'docker'
  | 'monitoring'
  | 'documentation'

export interface CICDConfig {
  /** Which CI/CD tool/file format this node represents */
  tool: 'github-actions' | 'gitlab-ci' | 'jenkins' | 'argocd' | 'helm' | 'generic'
  /** Default pipeline config values shown in the Config tab */
  defaultConfig: {
    triggers?: string[] // e.g. ['push', 'pull_request', 'schedule']
    branches?: string[] // e.g. ['main', 'develop']
    runsOn?: string // runner label: 'ubuntu-latest', 'self-hosted'
    stages?: string[] // pipeline stages
    nodeVersion?: string
    pythonVersion?: string
    dockerRegistry?: string
    deployTarget?: string // 'kubernetes' | 'ecs' | 'appservice' | 'lambda' | 'custom'
    [key: string]: any
  }
}

export interface ComponentConfig {
  id: string
  name: string
  category: ComponentCategory
  provider?: CloudProvider
  serviceType?: ServiceType
  /** What kind of code/config this component generates during export */
  generatorType?: GeneratorType
  icon: any
  color: string
  description: string
  estimatedCost: {
    min: number // monthly cost in USD
    max: number
  }
  terraform?: {
    provider: 'aws' | 'gcp' | 'azure' | 'vercel' | 'cloudflare'
    resource: string
    defaultConfig: Record<string, any>
  }
  /** Present when generatorType === 'cicd' */
  cicd?: CICDConfig
  // For IaaS components - can contain children
  canContain?: string[] // IDs of components that can be children
  // For configurable components
  configurable?: {
    replicas?: boolean // VMs can have replicas
    size?: boolean // VM size selection
    osImage?: boolean // OS selection
    attachments?: string[] // What can attach to this (e.g., NSG to NIC or Subnet)
  }
}

export const COMPONENT_CATALOG: ComponentConfig[] = [
  // ==========================================
  // AZURE — Organisation (Landing Zone / Management Groups)
  // ==========================================
  {
    id: 'azure-landing-zone',
    name: 'Landing Zone',
    category: 'cloud',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Building2 as any,
    color: '#4338CA',
    description: 'Azure Landing Zone — top-level organisational boundary (tenant root group)',
    estimatedCost: { min: 0, max: 0 },
    canContain: ['azure-management-group', 'azure-subscription'],
    terraform: {
      provider: 'azure',
      resource: 'azurerm_management_group',
      defaultConfig: { display_name: 'Root Landing Zone' },
    },
  },
  {
    id: 'azure-management-group',
    name: 'Management Group',
    category: 'cloud',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Building2 as any,
    color: '#6366F1',
    description: 'Azure Management Group — organises subscriptions and applies governance policies',
    estimatedCost: { min: 0, max: 0 },
    canContain: ['azure-management-group', 'azure-subscription'],
    terraform: {
      provider: 'azure',
      resource: 'azurerm_management_group',
      defaultConfig: { display_name: 'Management Group' },
    },
  },
  {
    id: 'azure-subscription',
    name: 'Subscription',
    category: 'cloud',
    provider: 'azure',
    serviceType: 'iaas',
    icon: CreditCard as any,
    color: '#0078D4',
    description: 'Azure Subscription — billing container and access control boundary',
    estimatedCost: { min: 0, max: 0 },
    canContain: ['azure-resource-group'],
    terraform: {
      provider: 'azure',
      resource: 'azurerm_subscription',
      defaultConfig: { subscription_name: 'Subscription' },
    },
  },
  // ==========================================
  // AZURE IaaS - Networking
  // ==========================================
  {
    id: 'azure-resource-group',
    name: 'Resource Group',
    category: 'cloud',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Box,
    color: '#0078D4',
    description: 'Azure Resource Group - container for related resources',
    estimatedCost: { min: 0, max: 0 },
    canContain: [
      'azure-vnet',
      'azure-vm',
      'azure-vmss',
      'azure-nsg',
      'azure-lb',
      'azure-app-gw',
      'azure-sql',
      'azure-aks',
      'azure-functions',
      'azure-app-service',
      'azure-key-vault',
      'azure-cosmos',
      'azure-storage-account',
      'azure-managed-disk',
      'azure-public-ip',
      'azure-nic',
      'azure-firewall',
      'azure-bastion',
      'azure-nat-gateway',
      'azure-service-bus',
      'azure-event-hub',
      'azure-front-door',
      'azure-traffic-manager',
      'azure-route-table',
      'azure-availability-set',
      'azure-blob',
      'azure-file-share',
      'azure-express-route',
      'azure-ddos-protection',
      'azure-vpn-gateway',
    ],
    terraform: {
      provider: 'azure',
      resource: 'azurerm_resource_group',
      defaultConfig: { location: 'westeurope' },
    },
  },
  {
    id: 'azure-vnet',
    name: 'Virtual Network',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Network,
    color: '#0078D4',
    description: 'Azure Virtual Network (VNet) - isolated network in Azure',
    estimatedCost: { min: 0, max: 5 },
    canContain: ['azure-subnet', 'azure-bastion', 'azure-firewall', 'azure-vpn-gateway'],
    terraform: {
      provider: 'azure',
      resource: 'azurerm_virtual_network',
      defaultConfig: { address_space: ['10.0.0.0/16'] },
    },
  },
  {
    id: 'azure-subnet',
    name: 'Subnet',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Network,
    color: '#0078D4',
    description: 'Azure Subnet - network segment within VNet',
    estimatedCost: { min: 0, max: 0 },
    canContain: ['azure-vm', 'azure-nic'],
    configurable: { attachments: ['azure-nsg', 'azure-route-table'] },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_subnet',
      defaultConfig: { address_prefixes: ['10.0.1.0/24'] },
    },
  },
  {
    id: 'azure-nsg',
    name: 'Network Security Group',
    category: 'security',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Shield,
    color: '#0078D4',
    description: 'Azure NSG - firewall rules for VNet/Subnet/NIC',
    estimatedCost: { min: 0, max: 0 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_network_security_group',
      defaultConfig: {
        security_rules: [
          {
            name: 'Allow-HTTPS-Inbound',
            priority: 100,
            direction: 'Inbound',
            access: 'Allow',
            protocol: 'Tcp',
            source_port_range: '*',
            destination_port_range: '443',
            source_address_prefix: 'Internet',
            destination_address_prefix: '*',
            description: 'Allow HTTPS inbound traffic',
          },
          {
            name: 'Allow-HTTP-Inbound',
            priority: 110,
            direction: 'Inbound',
            access: 'Allow',
            protocol: 'Tcp',
            source_port_range: '*',
            destination_port_range: '80',
            source_address_prefix: 'Internet',
            destination_address_prefix: '*',
            description: 'Allow HTTP inbound traffic',
          },
          {
            name: 'Allow-SSH-Inbound',
            priority: 120,
            direction: 'Inbound',
            access: 'Allow',
            protocol: 'Tcp',
            source_port_range: '*',
            destination_port_range: '22',
            source_address_prefix: 'VirtualNetwork',
            destination_address_prefix: '*',
            description: 'Allow SSH from VNet only',
          },
          {
            name: 'Allow-RDP-Inbound',
            priority: 130,
            direction: 'Inbound',
            access: 'Allow',
            protocol: 'Tcp',
            source_port_range: '*',
            destination_port_range: '3389',
            source_address_prefix: 'VirtualNetwork',
            destination_address_prefix: '*',
            description: 'Allow RDP from VNet only',
          },
          {
            name: 'Allow-VNet-Inbound',
            priority: 200,
            direction: 'Inbound',
            access: 'Allow',
            protocol: '*',
            source_port_range: '*',
            destination_port_range: '*',
            source_address_prefix: 'VirtualNetwork',
            destination_address_prefix: 'VirtualNetwork',
            description: 'Allow intra-VNet traffic',
          },
          {
            name: 'Allow-AzureLoadBalancer-Inbound',
            priority: 210,
            direction: 'Inbound',
            access: 'Allow',
            protocol: '*',
            source_port_range: '*',
            destination_port_range: '*',
            source_address_prefix: 'AzureLoadBalancer',
            destination_address_prefix: '*',
            description: 'Allow Azure Load Balancer probes',
          },
          {
            name: 'Deny-All-Inbound',
            priority: 4096,
            direction: 'Inbound',
            access: 'Deny',
            protocol: '*',
            source_port_range: '*',
            destination_port_range: '*',
            source_address_prefix: '*',
            destination_address_prefix: '*',
            description: 'Deny all other inbound traffic',
          },
          {
            name: 'Allow-VNet-Outbound',
            priority: 100,
            direction: 'Outbound',
            access: 'Allow',
            protocol: '*',
            source_port_range: '*',
            destination_port_range: '*',
            source_address_prefix: 'VirtualNetwork',
            destination_address_prefix: 'VirtualNetwork',
            description: 'Allow intra-VNet outbound',
          },
          {
            name: 'Allow-Internet-Outbound',
            priority: 110,
            direction: 'Outbound',
            access: 'Allow',
            protocol: 'Tcp',
            source_port_range: '*',
            destination_port_range: '443',
            source_address_prefix: '*',
            destination_address_prefix: 'Internet',
            description: 'Allow HTTPS outbound to Internet',
          },
          {
            name: 'Deny-All-Outbound',
            priority: 4096,
            direction: 'Outbound',
            access: 'Deny',
            protocol: '*',
            source_port_range: '*',
            destination_port_range: '*',
            source_address_prefix: '*',
            destination_address_prefix: '*',
            description: 'Deny all other outbound traffic',
          },
        ],
      },
    },
  },
  {
    id: 'azure-nic',
    name: 'Network Interface',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Network,
    color: '#0078D4',
    description: 'Azure NIC - network interface for VMs',
    estimatedCost: { min: 0, max: 0 },
    configurable: { attachments: ['azure-nsg'] },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_network_interface',
      defaultConfig: {},
    },
  },
  {
    id: 'azure-public-ip',
    name: 'Public IP',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Globe,
    color: '#0078D4',
    description: 'Azure Public IP address',
    estimatedCost: { min: 3, max: 5 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_public_ip',
      defaultConfig: { allocation_method: 'Static', sku: 'Standard' },
    },
  },
  {
    id: 'azure-route-table',
    name: 'Route Table',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Network,
    color: '#0078D4',
    description: 'Azure Route Table - custom routing for subnets',
    estimatedCost: { min: 0, max: 0 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_route_table',
      defaultConfig: {},
    },
  },
  {
    id: 'azure-nat-gateway',
    name: 'NAT Gateway',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Network,
    color: '#0078D4',
    description: 'Azure NAT Gateway - outbound internet connectivity',
    estimatedCost: { min: 32, max: 45 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_nat_gateway',
      defaultConfig: {},
    },
  },
  {
    id: 'azure-vpn-gateway',
    name: 'VPN Gateway',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Lock,
    color: '#0078D4',
    description: 'Azure VPN Gateway - site-to-site/point-to-site VPN',
    estimatedCost: { min: 140, max: 600 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_virtual_network_gateway',
      defaultConfig: { type: 'Vpn', vpn_type: 'RouteBased' },
    },
  },
  {
    id: 'azure-express-route',
    name: 'ExpressRoute',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Network,
    color: '#0078D4',
    description: 'Azure ExpressRoute - private connection to Azure',
    estimatedCost: { min: 55, max: 5000 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_express_route_circuit',
      defaultConfig: {},
    },
  },
  {
    id: 'azure-bastion',
    name: 'Azure Bastion',
    category: 'security',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Shield,
    color: '#0078D4',
    description: 'Secure RDP/SSH access to VMs without public IP',
    estimatedCost: { min: 140, max: 700 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_bastion_host',
      defaultConfig: {},
    },
  },
  {
    id: 'azure-firewall',
    name: 'Azure Firewall',
    category: 'security',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Shield,
    color: '#0078D4',
    description: 'Managed firewall service for VNet',
    estimatedCost: { min: 912, max: 1500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_firewall',
      defaultConfig: { sku_tier: 'Standard' },
    },
  },
  {
    id: 'azure-ddos-protection',
    name: 'DDoS Protection',
    category: 'security',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Shield,
    color: '#0078D4',
    description: 'Azure DDoS Protection Plan',
    estimatedCost: { min: 2944, max: 2944 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_network_ddos_protection_plan',
      defaultConfig: {},
    },
  },
  // ==========================================
  // AZURE IaaS - Compute
  // ==========================================
  {
    id: 'azure-vm',
    name: 'Virtual Machine',
    category: 'compute',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Server,
    color: '#0078D4',
    description: 'Azure Virtual Machine - IaaS compute',
    estimatedCost: { min: 15, max: 2000 },
    configurable: {
      replicas: true,
      size: true,
      osImage: true,
      attachments: ['azure-nic', 'azure-managed-disk'],
    },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_linux_virtual_machine',
      defaultConfig: { size: 'Standard_B2s' },
    },
  },
  {
    id: 'azure-vmss',
    name: 'VM Scale Set',
    category: 'compute',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Server,
    color: '#0078D4',
    description: 'Azure VM Scale Set - auto-scaling VMs',
    estimatedCost: { min: 30, max: 5000 },
    configurable: { size: true, osImage: true },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_linux_virtual_machine_scale_set',
      defaultConfig: { instances: 2, sku: 'Standard_B2s' },
    },
  },
  {
    id: 'azure-availability-set',
    name: 'Availability Set',
    category: 'compute',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Server,
    color: '#0078D4',
    description: 'Azure Availability Set - HA for VMs',
    estimatedCost: { min: 0, max: 0 },
    canContain: ['azure-vm'],
    terraform: {
      provider: 'azure',
      resource: 'azurerm_availability_set',
      defaultConfig: { platform_fault_domain_count: 2, platform_update_domain_count: 5 },
    },
  },
  // ==========================================
  // AZURE IaaS - Storage
  // ==========================================
  {
    id: 'azure-storage-account',
    name: 'Storage Account',
    category: 'storage',
    provider: 'azure',
    serviceType: 'iaas',
    icon: HardDrive,
    color: '#0078D4',
    description: 'Azure Storage Account - blobs, files, queues, tables',
    estimatedCost: { min: 1, max: 500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_storage_account',
      defaultConfig: { account_tier: 'Standard', account_replication_type: 'LRS' },
    },
  },
  {
    id: 'azure-managed-disk',
    name: 'Managed Disk',
    category: 'storage',
    provider: 'azure',
    serviceType: 'iaas',
    icon: HardDrive,
    color: '#0078D4',
    description: 'Azure Managed Disk - persistent storage for VMs',
    estimatedCost: { min: 2, max: 500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_managed_disk',
      defaultConfig: { storage_account_type: 'Premium_LRS', disk_size_gb: 128 },
    },
  },
  {
    id: 'azure-file-share',
    name: 'File Share',
    category: 'storage',
    provider: 'azure',
    serviceType: 'iaas',
    icon: HardDrive,
    color: '#0078D4',
    description: 'Azure Files - SMB file share',
    estimatedCost: { min: 5, max: 200 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_storage_share',
      defaultConfig: { quota: 100 },
    },
  },
  // ==========================================
  // AZURE IaaS - Load Balancing
  // ==========================================
  {
    id: 'azure-lb',
    name: 'Load Balancer',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Network,
    color: '#0078D4',
    description: 'Azure Load Balancer - L4 load balancing',
    estimatedCost: { min: 18, max: 100 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_lb',
      defaultConfig: { sku: 'Standard' },
    },
  },
  {
    id: 'azure-app-gw',
    name: 'Application Gateway',
    category: 'networking',
    provider: 'azure',
    serviceType: 'iaas',
    icon: Network,
    color: '#0078D4',
    description: 'Azure Application Gateway - L7 load balancer with WAF',
    estimatedCost: { min: 175, max: 700 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_application_gateway',
      defaultConfig: { sku: { name: 'Standard_v2', tier: 'Standard_v2' } },
    },
  },
  {
    id: 'azure-front-door',
    name: 'Front Door',
    category: 'networking',
    provider: 'azure',
    serviceType: 'paas',
    icon: Globe,
    color: '#0078D4',
    description: 'Azure Front Door - global load balancer with CDN',
    estimatedCost: { min: 35, max: 500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_frontdoor',
      defaultConfig: {},
    },
  },
  {
    id: 'azure-traffic-manager',
    name: 'Traffic Manager',
    category: 'networking',
    provider: 'azure',
    serviceType: 'paas',
    icon: Globe,
    color: '#0078D4',
    description: 'Azure Traffic Manager - DNS-based traffic routing',
    estimatedCost: { min: 0.5, max: 50 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_traffic_manager_profile',
      defaultConfig: { traffic_routing_method: 'Performance' },
    },
  },
  // ==========================================
  // AWS IaaS - Networking
  // ==========================================
  {
    id: 'aws-vpc',
    name: 'VPC',
    category: 'networking',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Network,
    color: '#FF9900',
    description: 'AWS Virtual Private Cloud - isolated network',
    estimatedCost: { min: 0, max: 5 },
    canContain: [
      'aws-subnet',
      'aws-internet-gateway',
      'aws-nat-gateway',
      'aws-route-table',
      'aws-security-group',
    ],
    terraform: {
      provider: 'aws',
      resource: 'aws_vpc',
      defaultConfig: { cidr_block: '10.0.0.0/16' },
    },
  },
  {
    id: 'aws-subnet',
    name: 'Subnet',
    category: 'networking',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Network,
    color: '#FF9900',
    description: 'AWS Subnet - network segment in VPC',
    estimatedCost: { min: 0, max: 0 },
    canContain: ['aws-ec2'],
    terraform: {
      provider: 'aws',
      resource: 'aws_subnet',
      defaultConfig: { cidr_block: '10.0.1.0/24' },
    },
  },
  {
    id: 'aws-security-group',
    name: 'Security Group',
    category: 'security',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Shield,
    color: '#FF9900',
    description: 'AWS Security Group - virtual firewall',
    estimatedCost: { min: 0, max: 0 },
    terraform: {
      provider: 'aws',
      resource: 'aws_security_group',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-internet-gateway',
    name: 'Internet Gateway',
    category: 'networking',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Globe,
    color: '#FF9900',
    description: 'AWS Internet Gateway - connect VPC to internet',
    estimatedCost: { min: 0, max: 0 },
    terraform: {
      provider: 'aws',
      resource: 'aws_internet_gateway',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-nat-gateway',
    name: 'NAT Gateway',
    category: 'networking',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Network,
    color: '#FF9900',
    description: 'AWS NAT Gateway - outbound internet for private subnets',
    estimatedCost: { min: 32, max: 100 },
    terraform: {
      provider: 'aws',
      resource: 'aws_nat_gateway',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-route-table',
    name: 'Route Table',
    category: 'networking',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Network,
    color: '#FF9900',
    description: 'AWS Route Table - routing for subnets',
    estimatedCost: { min: 0, max: 0 },
    terraform: {
      provider: 'aws',
      resource: 'aws_route_table',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-elastic-ip',
    name: 'Elastic IP',
    category: 'networking',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Globe,
    color: '#FF9900',
    description: 'AWS Elastic IP - static public IP',
    estimatedCost: { min: 3.6, max: 5 },
    terraform: {
      provider: 'aws',
      resource: 'aws_eip',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-alb',
    name: 'Application Load Balancer',
    category: 'networking',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Network,
    color: '#FF9900',
    description: 'AWS ALB - L7 load balancer',
    estimatedCost: { min: 16, max: 200 },
    terraform: {
      provider: 'aws',
      resource: 'aws_lb',
      defaultConfig: { load_balancer_type: 'application' },
    },
  },
  {
    id: 'aws-nlb',
    name: 'Network Load Balancer',
    category: 'networking',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Network,
    color: '#FF9900',
    description: 'AWS NLB - L4 load balancer',
    estimatedCost: { min: 16, max: 200 },
    terraform: {
      provider: 'aws',
      resource: 'aws_lb',
      defaultConfig: { load_balancer_type: 'network' },
    },
  },
  {
    id: 'aws-cloudfront',
    name: 'CloudFront',
    category: 'networking',
    provider: 'aws',
    serviceType: 'paas',
    icon: Globe,
    color: '#FF9900',
    description: 'AWS CloudFront - CDN',
    estimatedCost: { min: 0, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_cloudfront_distribution',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-route53',
    name: 'Route 53',
    category: 'networking',
    provider: 'aws',
    serviceType: 'paas',
    icon: Globe,
    color: '#FF9900',
    description: 'AWS Route 53 - DNS service',
    estimatedCost: { min: 0.5, max: 50 },
    terraform: {
      provider: 'aws',
      resource: 'aws_route53_zone',
      defaultConfig: {},
    },
  },
  // ==========================================
  // AWS IaaS - Compute
  // ==========================================
  {
    id: 'aws-ec2',
    name: 'EC2 Instance',
    category: 'compute',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Server,
    color: '#FF9900',
    description: 'AWS EC2 - virtual servers',
    estimatedCost: { min: 8, max: 2000 },
    configurable: { replicas: true, size: true, osImage: true },
    terraform: {
      provider: 'aws',
      resource: 'aws_instance',
      defaultConfig: { instance_type: 't3.micro' },
    },
  },
  {
    id: 'aws-auto-scaling',
    name: 'Auto Scaling Group',
    category: 'compute',
    provider: 'aws',
    serviceType: 'iaas',
    icon: Server,
    color: '#FF9900',
    description: 'AWS Auto Scaling - automatically scale EC2',
    estimatedCost: { min: 0, max: 0 },
    terraform: {
      provider: 'aws',
      resource: 'aws_autoscaling_group',
      defaultConfig: { min_size: 1, max_size: 10 },
    },
  },
  // ==========================================
  // AWS IaaS - Storage
  // ==========================================
  {
    id: 'aws-s3',
    name: 'S3 Bucket',
    category: 'storage',
    provider: 'aws',
    serviceType: 'iaas',
    icon: HardDrive,
    color: '#FF9900',
    description: 'AWS S3 - object storage',
    estimatedCost: { min: 0, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_s3_bucket',
      defaultConfig: {
        versioning: {
          enabled: true,
        },
      },
    },
  },
  {
    id: 'aws-ebs',
    name: 'EBS Volume',
    category: 'storage',
    provider: 'aws',
    serviceType: 'iaas',
    icon: HardDrive,
    color: '#FF9900',
    description: 'AWS EBS - block storage for EC2',
    estimatedCost: { min: 2, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_ebs_volume',
      defaultConfig: { type: 'gp3', size: 100 },
    },
  },
  {
    id: 'aws-efs',
    name: 'EFS File System',
    category: 'storage',
    provider: 'aws',
    serviceType: 'iaas',
    icon: HardDrive,
    color: '#FF9900',
    description: 'AWS EFS - managed NFS',
    estimatedCost: { min: 5, max: 300 },
    terraform: {
      provider: 'aws',
      resource: 'aws_efs_file_system',
      defaultConfig: {},
    },
  },
  // ==========================================
  // GCP IaaS - Networking
  // ==========================================
  {
    id: 'gcp-vpc',
    name: 'VPC Network',
    category: 'networking',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: Network,
    color: '#4285F4',
    description: 'GCP VPC - virtual private cloud',
    estimatedCost: { min: 0, max: 5 },
    canContain: ['gcp-subnet', 'gcp-cloud-nat', 'gcp-firewall'],
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_network',
      defaultConfig: { auto_create_subnetworks: false },
    },
  },
  {
    id: 'gcp-subnet',
    name: 'Subnetwork',
    category: 'networking',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: Network,
    color: '#4285F4',
    description: 'GCP Subnet - regional subnet in VPC',
    estimatedCost: { min: 0, max: 0 },
    canContain: ['gcp-compute-instance'],
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_subnetwork',
      defaultConfig: { ip_cidr_range: '10.0.1.0/24' },
    },
  },
  {
    id: 'gcp-firewall',
    name: 'Firewall Rule',
    category: 'security',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: Shield,
    color: '#4285F4',
    description: 'GCP Firewall - network-level firewall',
    estimatedCost: { min: 0, max: 0 },
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_firewall',
      defaultConfig: {},
    },
  },
  {
    id: 'gcp-cloud-nat',
    name: 'Cloud NAT',
    category: 'networking',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: Network,
    color: '#4285F4',
    description: 'GCP Cloud NAT - managed NAT gateway',
    estimatedCost: { min: 32, max: 100 },
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_router_nat',
      defaultConfig: {},
    },
  },
  {
    id: 'gcp-cloud-lb',
    name: 'Cloud Load Balancer',
    category: 'networking',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: Network,
    color: '#4285F4',
    description: 'GCP Load Balancer - global/regional LB',
    estimatedCost: { min: 18, max: 200 },
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_global_forwarding_rule',
      defaultConfig: {},
    },
  },
  {
    id: 'gcp-cloud-cdn',
    name: 'Cloud CDN',
    category: 'networking',
    provider: 'gcp',
    serviceType: 'paas',
    icon: Globe,
    color: '#4285F4',
    description: 'GCP Cloud CDN - content delivery',
    estimatedCost: { min: 0, max: 200 },
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_backend_service',
      defaultConfig: { enable_cdn: true },
    },
  },
  // ==========================================
  // GCP IaaS - Compute
  // ==========================================
  {
    id: 'gcp-compute-instance',
    name: 'Compute Engine',
    category: 'compute',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: Server,
    color: '#4285F4',
    description: 'GCP VM - virtual machine',
    estimatedCost: { min: 5, max: 2000 },
    configurable: { replicas: true, size: true, osImage: true },
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_instance',
      defaultConfig: { machine_type: 'e2-medium' },
    },
  },
  {
    id: 'gcp-instance-group',
    name: 'Instance Group',
    category: 'compute',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: Server,
    color: '#4285F4',
    description: 'GCP Managed Instance Group - auto-scaling',
    estimatedCost: { min: 10, max: 5000 },
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_instance_group_manager',
      defaultConfig: { target_size: 2 },
    },
  },
  // ==========================================
  // GCP IaaS - Storage
  // ==========================================
  {
    id: 'gcp-cloud-storage',
    name: 'Cloud Storage',
    category: 'storage',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: HardDrive,
    color: '#4285F4',
    description: 'GCP Cloud Storage - object storage',
    estimatedCost: { min: 0, max: 500 },
    terraform: {
      provider: 'gcp',
      resource: 'google_storage_bucket',
      defaultConfig: { location: 'EU' },
    },
  },
  {
    id: 'gcp-persistent-disk',
    name: 'Persistent Disk',
    category: 'storage',
    provider: 'gcp',
    serviceType: 'iaas',
    icon: HardDrive,
    color: '#4285F4',
    description: 'GCP Persistent Disk - block storage',
    estimatedCost: { min: 2, max: 500 },
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_disk',
      defaultConfig: { type: 'pd-ssd', size: 100 },
    },
  },
  // ==========================================
  // Frontend Components
  // ==========================================
  {
    id: 'react-app',
    name: 'React Application',
    category: 'frontend',
    serviceType: 'generic',
    icon: Code,
    color: '#61DAFB',
    description: 'Single Page Application built with React',
    estimatedCost: { min: 0, max: 50 },
    terraform: {
      provider: 'vercel',
      resource: 'vercel_project',
      defaultConfig: {
        framework: 'react',
      },
    },
  },
  {
    id: 'nextjs-app',
    serviceType: 'hosting',
    name: 'Next.js Application',
    category: 'frontend',
    icon: Code,
    color: '#000000',
    description: 'Full-stack React framework with SSR/SSG',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'vercel',
      resource: 'vercel_project',
      defaultConfig: {
        framework: 'nextjs',
      },
    },
  },
  {
    id: 'vue-app',
    serviceType: 'hosting',
    name: 'Vue.js Application',
    category: 'frontend',
    icon: Code,
    color: '#42B883',
    description: 'Progressive JavaScript framework',
    estimatedCost: { min: 0, max: 50 },
  },
  {
    id: 'angular-app',
    serviceType: 'hosting',
    name: 'Angular Application',
    category: 'frontend',
    icon: Code,
    color: '#DD0031',
    description: 'TypeScript-based web framework',
    estimatedCost: { min: 0, max: 50 },
  },
  {
    id: 'static-site',
    serviceType: 'hosting',
    name: 'Static Website',
    category: 'frontend',
    icon: Globe,
    color: '#FF6B6B',
    description: 'HTML/CSS/JS static website',
    estimatedCost: { min: 0, max: 20 },
    terraform: {
      provider: 'aws',
      resource: 'aws_s3_bucket',
      defaultConfig: {
        website: {
          index_document: 'index.html',
        },
      },
    },
  },

  // Backend Components
  {
    id: 'nodejs-api',
    serviceType: 'paas',
    name: 'Node.js API',
    category: 'backend',
    icon: Server,
    color: '#339933',
    description: 'RESTful API built with Node.js/Express',
    estimatedCost: { min: 5, max: 200 },
    terraform: {
      provider: 'aws',
      resource: 'aws_ecs_service',
      defaultConfig: {
        launch_type: 'FARGATE',
      },
    },
  },
  {
    id: 'python-api',
    serviceType: 'paas',
    name: 'Python API',
    category: 'backend',
    icon: Server,
    color: '#3776AB',
    description: 'FastAPI/Django REST API',
    estimatedCost: { min: 5, max: 200 },
  },
  {
    id: 'go-api',
    serviceType: 'paas',
    name: 'Go API',
    category: 'backend',
    icon: Server,
    color: '#00ADD8',
    description: 'High-performance Go API',
    estimatedCost: { min: 5, max: 200 },
  },
  {
    id: 'java-api',
    serviceType: 'paas',
    name: 'Java API',
    category: 'backend',
    icon: Server,
    color: '#007396',
    description: 'Spring Boot REST API',
    estimatedCost: { min: 10, max: 300 },
  },
  {
    id: 'dotnet-api',
    serviceType: 'paas',
    name: '.NET API',
    category: 'backend',
    icon: Server,
    color: '#512BD4',
    description: 'ASP.NET Core Web API',
    estimatedCost: { min: 10, max: 300 },
  },
  {
    id: 'ruby-api',
    serviceType: 'paas',
    name: 'Ruby API',
    category: 'backend',
    icon: Server,
    color: '#CC342D',
    description: 'Ruby on Rails API',
    estimatedCost: { min: 5, max: 200 },
  },

  // Database Components
  {
    id: 'postgresql',
    serviceType: 'paas',
    name: 'PostgreSQL',
    category: 'database',
    icon: Database,
    color: '#336791',
    description: 'Relational database',
    estimatedCost: { min: 15, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_db_instance',
      defaultConfig: {
        engine: 'postgres',
        engine_version: '15.3',
        instance_class: 'db.t3.micro',
      },
    },
  },
  {
    id: 'mysql',
    serviceType: 'paas',
    name: 'MySQL',
    category: 'database',
    icon: Database,
    color: '#4479A1',
    description: 'Popular relational database',
    estimatedCost: { min: 15, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_db_instance',
      defaultConfig: {
        engine: 'mysql',
        engine_version: '8.0',
        instance_class: 'db.t3.micro',
      },
    },
  },
  {
    id: 'mongodb',
    serviceType: 'paas',
    name: 'MongoDB',
    category: 'database',
    icon: Database,
    color: '#47A248',
    description: 'Document-oriented NoSQL database',
    estimatedCost: { min: 25, max: 1000 },
  },
  {
    id: 'redis',
    serviceType: 'paas',
    name: 'Redis',
    category: 'database',
    icon: Database,
    color: '#DC382D',
    description: 'In-memory cache and message broker',
    estimatedCost: { min: 10, max: 300 },
    terraform: {
      provider: 'aws',
      resource: 'aws_elasticache_cluster',
      defaultConfig: {
        engine: 'redis',
        node_type: 'cache.t3.micro',
      },
    },
  },
  {
    id: 'supabase',
    serviceType: 'paas',
    name: 'Supabase',
    category: 'database',
    icon: Database,
    color: '#3ECF8E',
    description: 'Open-source Firebase alternative with Postgres',
    estimatedCost: { min: 0, max: 100 },
  },
  {
    id: 'dynamodb',
    serviceType: 'paas',
    name: 'DynamoDB',
    category: 'database',
    icon: Database,
    color: '#4053D6',
    description: 'AWS NoSQL database',
    estimatedCost: { min: 0, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_dynamodb_table',
      defaultConfig: {
        billing_mode: 'PAY_PER_REQUEST',
      },
    },
  },

  // Cloud Services - AWS
  {
    id: 'aws-lambda',
    serviceType: 'paas',
    name: 'AWS Lambda',
    category: 'cloud',
    icon: Zap,
    color: '#FF9900',
    description: 'Serverless compute service',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'aws',
      resource: 'aws_lambda_function',
      defaultConfig: {
        runtime: 'nodejs18.x',
        memory_size: 128,
        timeout: 30,
      },
    },
  },
  {
    id: 'aws-ecs',
    serviceType: 'paas',
    name: 'AWS ECS',
    category: 'cloud',
    icon: Container,
    color: '#FF9900',
    description: 'Container orchestration service',
    estimatedCost: { min: 30, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_ecs_cluster',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-api-gateway',
    serviceType: 'paas',
    name: 'AWS API Gateway',
    category: 'cloud',
    icon: Network,
    color: '#FF9900',
    description: 'API management service',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'aws',
      resource: 'aws_api_gateway_rest_api',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-sqs',
    serviceType: 'paas',
    name: 'AWS SQS',
    category: 'service',
    icon: MessageSquare,
    color: '#FF9900',
    description: 'Message queue service',
    estimatedCost: { min: 0, max: 50 },
    terraform: {
      provider: 'aws',
      resource: 'aws_sqs_queue',
      defaultConfig: {
        visibility_timeout_seconds: 30,
      },
    },
  },

  // Cloud Services - GCP
  {
    id: 'gcp-cloud-run',
    serviceType: 'paas',
    name: 'GCP Cloud Run',
    category: 'cloud',
    icon: Container,
    color: '#4285F4',
    description: 'Serverless container platform',
    estimatedCost: { min: 0, max: 200 },
    terraform: {
      provider: 'gcp',
      resource: 'google_cloud_run_service',
      defaultConfig: {},
    },
  },
  {
    id: 'gcp-cloud-functions',
    serviceType: 'paas',
    name: 'GCP Cloud Functions',
    category: 'cloud',
    icon: Zap,
    color: '#4285F4',
    description: 'Serverless functions',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'gcp',
      resource: 'google_cloudfunctions_function',
      defaultConfig: {
        runtime: 'nodejs18',
      },
    },
  },

  // Cloud Services - Azure
  {
    id: 'azure-functions',
    serviceType: 'paas',
    name: 'Azure Functions',
    category: 'cloud',
    provider: 'azure',
    icon: Zap,
    color: '#0078D4',
    description: 'Serverless compute',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_linux_function_app',
      defaultConfig: {
        os_type: 'Linux',
        sku_name: 'Y1',
        runtime_stack: 'node',
        runtime_version: '20',
        https_only: true,
      },
    },
  },
  {
    id: 'azure-app-service',
    serviceType: 'paas',
    name: 'Azure App Service',
    category: 'cloud',
    provider: 'azure',
    icon: Server,
    color: '#0078D4',
    description: 'Web app hosting',
    estimatedCost: { min: 10, max: 300 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_linux_web_app',
      defaultConfig: {
        sku_name: 'B1',
        https_only: true,
        always_on: true,
        runtime_stack: 'NODE',
        runtime_version: '20-lts',
      },
    },
  },

  // Additional Services
  {
    id: 'kubernetes',
    serviceType: 'iaas',
    name: 'Kubernetes Cluster',
    category: 'cloud',
    icon: Container,
    color: '#326CE5',
    description: 'Container orchestration platform',
    estimatedCost: { min: 100, max: 2000 },
  },
  {
    id: 'cloudflare-workers',
    serviceType: 'hosting',
    name: 'Cloudflare Workers',
    category: 'cloud',
    icon: Zap,
    color: '#F38020',
    description: 'Edge serverless functions',
    estimatedCost: { min: 0, max: 50 },
  },
  {
    id: 'vercel',
    serviceType: 'hosting',
    name: 'Vercel Hosting',
    category: 'cloud',
    icon: Globe,
    color: '#000000',
    description: 'Frontend hosting platform',
    estimatedCost: { min: 0, max: 50 },
  },
  {
    id: 'auth-service',
    serviceType: 'paas',
    name: 'Auth Service',
    category: 'service',
    icon: Lock,
    color: '#6366F1',
    description: 'User authentication system',
    estimatedCost: { min: 0, max: 50 },
  },
  {
    id: 'email-service',
    serviceType: 'saas',
    name: 'Email Service',
    category: 'service',
    icon: Mail,
    color: '#8B5CF6',
    description: 'Transactional email service',
    estimatedCost: { min: 0, max: 30 },
  },
  {
    id: 'cdn',
    serviceType: 'iaas',
    name: 'CDN',
    category: 'service',
    icon: Network,
    color: '#EC4899',
    description: 'Content delivery network',
    estimatedCost: { min: 0, max: 100 },
  },
  {
    id: 'monitoring',
    serviceType: 'saas',
    name: 'Monitoring Service',
    category: 'service',
    icon: Activity,
    color: '#10B981',
    description: 'Application monitoring and logging',
    estimatedCost: { min: 0, max: 100 },
  },

  // Additional AWS Services
  {
    id: 'aws-rds',
    serviceType: 'paas',
    name: 'AWS RDS',
    category: 'database',
    provider: 'aws',
    icon: Database,
    color: '#FF9900',
    description: 'Managed relational database service',
    estimatedCost: { min: 15, max: 1000 },
    terraform: {
      provider: 'aws',
      resource: 'aws_db_instance',
      defaultConfig: { engine: 'postgres', instance_class: 'db.t3.micro' },
    },
  },
  {
    id: 'aws-aurora',
    serviceType: 'paas',
    name: 'AWS Aurora',
    category: 'database',
    provider: 'aws',
    icon: Database,
    color: '#FF9900',
    description:
      'High-performance managed relational database compatible with MySQL and PostgreSQL',
    estimatedCost: { min: 60, max: 2000 },
    terraform: {
      provider: 'aws',
      resource: 'aws_rds_cluster',
      defaultConfig: { engine: 'aurora-postgresql', engine_version: '15.4' },
    },
  },
  {
    id: 'aws-aurora-serverless',
    serviceType: 'paas',
    name: 'AWS Aurora Serverless',
    category: 'database',
    provider: 'aws',
    icon: Database,
    color: '#FF9900',
    description: 'On-demand auto-scaling Aurora database — scales capacity automatically',
    estimatedCost: { min: 5, max: 1500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_rds_cluster',
      defaultConfig: {
        engine: 'aurora-postgresql',
        engine_mode: 'serverless',
        engine_version: '15.4',
      },
    },
  },
  {
    id: 'aws-eks',
    serviceType: 'iaas',
    name: 'AWS EKS',
    category: 'cloud',
    provider: 'aws',
    icon: Container,
    color: '#FF9900',
    description: 'Managed Kubernetes service',
    estimatedCost: { min: 73, max: 3000 },
    terraform: {
      provider: 'aws',
      resource: 'aws_eks_cluster',
      defaultConfig: {
        kubernetes_version: '1.31',
        endpoint_private_access: true,
        endpoint_public_access: true,
        instance_types: ['m5.large'],
        desired_size: 2,
        min_size: 1,
        max_size: 5,
      },
    },
  },
  {
    id: 'aws-sns',
    serviceType: 'paas',
    name: 'AWS SNS',
    category: 'service',
    provider: 'aws',
    icon: Radio,
    color: '#FF9900',
    description: 'Pub/Sub messaging service',
    estimatedCost: { min: 0, max: 50 },
    terraform: {
      provider: 'aws',
      resource: 'aws_sns_topic',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-cognito',
    serviceType: 'paas',
    name: 'AWS Cognito',
    category: 'security',
    provider: 'aws',
    icon: Users,
    color: '#FF9900',
    description: 'User authentication and authorization',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'aws',
      resource: 'aws_cognito_user_pool',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-secrets-manager',
    serviceType: 'paas',
    name: 'AWS Secrets Manager',
    category: 'security',
    provider: 'aws',
    icon: Key,
    color: '#FF9900',
    description: 'Manage secrets and credentials',
    estimatedCost: { min: 0.4, max: 50 },
    terraform: {
      provider: 'aws',
      resource: 'aws_secretsmanager_secret',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-step-functions',
    serviceType: 'paas',
    name: 'AWS Step Functions',
    category: 'service',
    provider: 'aws',
    icon: Workflow,
    color: '#FF9900',
    description: 'Workflow orchestration',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'aws',
      resource: 'aws_sfn_state_machine',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-eventbridge',
    serviceType: 'paas',
    name: 'AWS EventBridge',
    category: 'service',
    provider: 'aws',
    icon: Zap,
    color: '#FF9900',
    description: 'Event-driven architecture',
    estimatedCost: { min: 0, max: 50 },
    terraform: {
      provider: 'aws',
      resource: 'aws_cloudwatch_event_bus',
      defaultConfig: {},
    },
  },
  {
    id: 'aws-elb',
    serviceType: 'iaas',
    name: 'AWS Load Balancer',
    category: 'cloud',
    provider: 'aws',
    icon: Network,
    color: '#FF9900',
    description: 'Application Load Balancer',
    estimatedCost: { min: 20, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_lb',
      defaultConfig: { load_balancer_type: 'application' },
    },
  },
  {
    id: 'aws-elasticache',
    serviceType: 'paas',
    name: 'AWS ElastiCache',
    category: 'database',
    provider: 'aws',
    icon: Database,
    color: '#FF9900',
    description: 'In-memory caching service',
    estimatedCost: { min: 15, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_elasticache_cluster',
      defaultConfig: { engine: 'redis', node_type: 'cache.t3.micro' },
    },
  },
  {
    id: 'aws-redshift',
    serviceType: 'paas',
    name: 'AWS Redshift',
    category: 'analytics',
    provider: 'aws',
    icon: Database,
    color: '#FF9900',
    description: 'Petabyte-scale data warehouse for analytics workloads',
    estimatedCost: { min: 180, max: 5000 },
    terraform: {
      provider: 'aws',
      resource: 'aws_redshift_cluster',
      defaultConfig: { cluster_type: 'single-node', node_type: 'dc2.large', number_of_nodes: 1 },
    },
  },
  {
    id: 'aws-kinesis',
    serviceType: 'paas',
    name: 'AWS Kinesis',
    category: 'analytics',
    provider: 'aws',
    icon: Activity,
    color: '#FF9900',
    description: 'Real-time data streaming',
    estimatedCost: { min: 15, max: 500 },
    terraform: {
      provider: 'aws',
      resource: 'aws_kinesis_stream',
      defaultConfig: { shard_count: 1 },
    },
  },
  // Additional GCP Services
  {
    id: 'gcp-compute-engine',
    serviceType: 'iaas',
    name: 'GCP Compute Engine',
    category: 'cloud',
    provider: 'gcp',
    icon: Server,
    color: '#4285F4',
    description: 'Virtual machines on GCP',
    estimatedCost: { min: 5, max: 2000 },
    terraform: {
      provider: 'gcp',
      resource: 'google_compute_instance',
      defaultConfig: { machine_type: 'e2-micro' },
    },
  },
  {
    id: 'gcp-gke',
    serviceType: 'iaas',
    name: 'GCP GKE',
    category: 'cloud',
    provider: 'gcp',
    icon: Container,
    color: '#4285F4',
    description: 'Managed Kubernetes service',
    estimatedCost: { min: 73, max: 3000 },
    terraform: {
      provider: 'gcp',
      resource: 'google_container_cluster',
      defaultConfig: {
        initial_node_count: 1,
        remove_default_node_pool: true,
        deletion_protection: false,
        machine_type: 'n2-standard-2',
        disk_size_gb: 100,
        disk_type: 'pd-standard',
        min_count: 1,
        max_count: 5,
        auto_repair: true,
        auto_upgrade: true,
        network: 'default',
        subnetwork: 'default',
      },
    },
  },
  {
    id: 'gcp-cloud-sql',
    serviceType: 'paas',
    name: 'GCP Cloud SQL',
    category: 'database',
    provider: 'gcp',
    icon: Database,
    color: '#4285F4',
    description: 'Managed MySQL/PostgreSQL',
    estimatedCost: { min: 10, max: 1000 },
    terraform: {
      provider: 'gcp',
      resource: 'google_sql_database_instance',
      defaultConfig: { database_version: 'POSTGRES_14' },
    },
  },
  {
    id: 'gcp-firestore',
    serviceType: 'paas',
    name: 'GCP Firestore',
    category: 'database',
    provider: 'gcp',
    icon: Database,
    color: '#4285F4',
    description: 'Serverless NoSQL document database with real-time sync',
    estimatedCost: { min: 0, max: 500 },
    terraform: {
      provider: 'gcp',
      resource: 'google_firestore_database',
      defaultConfig: { type: 'FIRESTORE_NATIVE', location_id: 'us-central1' },
    },
  },
  {
    id: 'gcp-spanner',
    serviceType: 'paas',
    name: 'GCP Cloud Spanner',
    category: 'database',
    provider: 'gcp',
    icon: Database,
    color: '#4285F4',
    description: 'Globally distributed relational database with strong consistency',
    estimatedCost: { min: 65, max: 5000 },
    terraform: {
      provider: 'gcp',
      resource: 'google_spanner_instance',
      defaultConfig: { num_nodes: 1, display_name: 'Main Instance' },
    },
  },
  {
    id: 'gcp-memorystore',
    serviceType: 'paas',
    name: 'GCP Memorystore',
    category: 'database',
    provider: 'gcp',
    icon: Database,
    color: '#4285F4',
    description: 'Managed Redis and Memcached in-memory data store',
    estimatedCost: { min: 13, max: 500 },
    terraform: {
      provider: 'gcp',
      resource: 'google_redis_instance',
      defaultConfig: { tier: 'BASIC', memory_size_gb: 1 },
    },
  },
  {
    id: 'gcp-secret-manager',
    serviceType: 'paas',
    name: 'GCP Secret Manager',
    category: 'security',
    provider: 'gcp',
    icon: Key,
    color: '#4285F4',
    description: 'Managed secrets storage with automatic rotation',
    estimatedCost: { min: 0, max: 10 },
    terraform: {
      provider: 'gcp',
      resource: 'google_secret_manager_secret',
      defaultConfig: { replication: { automatic: true } },
    },
  },
  {
    id: 'gcp-cloud-dns',
    serviceType: 'paas',
    name: 'GCP Cloud DNS',
    category: 'networking',
    provider: 'gcp',
    icon: Globe,
    color: '#4285F4',
    description: 'Scalable managed DNS service with global anycast',
    estimatedCost: { min: 0.2, max: 10 },
    terraform: {
      provider: 'gcp',
      resource: 'google_dns_managed_zone',
      defaultConfig: { dns_name: 'example.com.', visibility: 'public' },
    },
  },
  {
    id: 'gcp-pubsub',
    serviceType: 'paas',
    name: 'GCP Pub/Sub',
    category: 'service',
    provider: 'gcp',
    icon: MessageSquare,
    color: '#4285F4',
    description: 'Messaging service',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'gcp',
      resource: 'google_pubsub_topic',
      defaultConfig: {},
    },
  },
  {
    id: 'gcp-bigquery',
    serviceType: 'paas',
    name: 'GCP BigQuery',
    category: 'analytics',
    provider: 'gcp',
    icon: BarChart,
    color: '#4285F4',
    description: 'Data warehouse analytics',
    estimatedCost: { min: 0, max: 1000 },
    terraform: {
      provider: 'gcp',
      resource: 'google_bigquery_dataset',
      defaultConfig: {},
    },
  },
  {
    id: 'gcp-firebase',
    serviceType: 'paas',
    name: 'GCP Firebase',
    category: 'service',
    provider: 'gcp',
    icon: Zap,
    color: '#FFCA28',
    description: 'App development platform',
    estimatedCost: { min: 0, max: 200 },
  },

  // Additional Azure Services
  {
    id: 'azure-aks',
    serviceType: 'iaas',
    name: 'Azure AKS',
    category: 'cloud',
    provider: 'azure',
    icon: Container,
    color: '#0078D4',
    description: 'Managed Kubernetes service',
    estimatedCost: { min: 73, max: 3000 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_kubernetes_cluster',
      defaultConfig: {
        dns_prefix: 'myaks',
        kubernetes_version: '1.31',
        node_count: 2,
        vm_size: 'Standard_D2s_v3',
        os_disk_size_gb: 128,
        identity_type: 'SystemAssigned',
        sku_tier: 'Free',
        network_plugin: 'azure',
        network_policy: 'azure',
        load_balancer_sku: 'standard',
      },
    },
  },
  {
    id: 'azure-container-apps',
    serviceType: 'paas',
    name: 'Azure Container Apps',
    category: 'cloud',
    provider: 'azure',
    icon: Container,
    color: '#0078D4',
    description: 'Serverless container hosting — run microservices without managing infrastructure',
    estimatedCost: { min: 0, max: 500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_container_app',
      defaultConfig: {
        revision_mode: 'Single',
        ingress_external_enabled: true,
        ingress_target_port: 80,
        min_replicas: 0,
        max_replicas: 10,
      },
    },
  },
  {
    id: 'azure-sql',
    serviceType: 'paas',
    name: 'Azure SQL Database',
    category: 'database',
    provider: 'azure',
    icon: Database,
    color: '#0078D4',
    description: 'Managed SQL database',
    estimatedCost: { min: 15, max: 1000 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_mssql_database',
      defaultConfig: {
        sku_name: 'S0',
        max_size_gb: 50,
        collation: 'SQL_Latin1_General_CP1_CI_AS',
        zone_redundant: false,
        read_scale: false,
      },
    },
  },
  {
    id: 'azure-blob',
    serviceType: 'paas',
    name: 'Azure Blob Storage',
    category: 'cloud',
    provider: 'azure',
    icon: HardDrive,
    color: '#0078D4',
    description: 'Object storage service',
    estimatedCost: { min: 0, max: 100 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_storage_account',
      defaultConfig: {
        account_tier: 'Standard',
        account_replication_type: 'LRS',
        account_kind: 'StorageV2',
        access_tier: 'Hot',
        min_tls_version: 'TLS1_2',
        allow_nested_items_to_be_public: false,
      },
    },
  },
  {
    id: 'azure-cosmos',
    serviceType: 'paas',
    name: 'Azure Cosmos DB',
    category: 'database',
    provider: 'azure',
    icon: Database,
    color: '#0078D4',
    description: 'Globally distributed NoSQL',
    estimatedCost: { min: 25, max: 2000 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_cosmosdb_account',
      defaultConfig: {
        offer_type: 'Standard',
        kind: 'GlobalDocumentDB',
        consistency_level: 'Session',
        geo_location_failover_priority: 0,
        enable_automatic_failover: false,
      },
    },
  },
  {
    id: 'azure-redis',
    serviceType: 'paas',
    name: 'Azure Cache for Redis',
    category: 'database',
    provider: 'azure',
    icon: Database,
    color: '#0078D4',
    description: 'Managed in-memory Redis cache for low-latency data access',
    estimatedCost: { min: 16, max: 1000 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_redis_cache',
      defaultConfig: {
        capacity: 0,
        family: 'C',
        sku_name: 'Basic',
        minimum_tls_version: '1.2',
      },
    },
  },
  {
    id: 'azure-cdn',
    serviceType: 'paas',
    name: 'Azure CDN',
    category: 'networking',
    provider: 'azure',
    icon: Globe,
    color: '#0078D4',
    description: 'Content delivery network for global static content distribution',
    estimatedCost: { min: 0.81, max: 500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_cdn_profile',
      defaultConfig: {
        sku: 'Standard_Microsoft',
      },
    },
  },
  {
    id: 'azure-sql-serverless',
    serviceType: 'paas',
    name: 'Azure SQL Serverless',
    category: 'database',
    provider: 'azure',
    icon: Database,
    color: '#0078D4',
    description: 'Auto-pausing serverless SQL database for intermittent workloads',
    estimatedCost: { min: 5, max: 500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_mssql_database',
      defaultConfig: {
        sku_name: 'GP_S_Gen5_1',
        auto_pause_delay_in_minutes: 60,
        min_capacity: 0.5,
      },
    },
  },
  {
    id: 'azure-event-hub',
    serviceType: 'paas',
    name: 'Azure Event Hubs',
    category: 'service',
    provider: 'azure',
    icon: Activity,
    color: '#0078D4',
    description: 'Big data streaming',
    estimatedCost: { min: 10, max: 500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_eventhub',
      defaultConfig: {
        partition_count: 2,
        message_retention: 1,
        namespace_sku: 'Standard',
        capacity: 1,
      },
    },
  },
  {
    id: 'azure-service-bus',
    serviceType: 'paas',
    name: 'Azure Service Bus',
    category: 'service',
    provider: 'azure',
    icon: MessageSquare,
    color: '#0078D4',
    description: 'Enterprise messaging',
    estimatedCost: { min: 0, max: 200 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_servicebus_namespace',
      defaultConfig: {
        sku: 'Standard',
        capacity: 0,
        zone_redundant: false,
      },
    },
  },
  {
    id: 'azure-ad',
    serviceType: 'paas',
    name: 'Azure Active Directory',
    category: 'security',
    provider: 'azure',
    icon: Shield,
    color: '#0078D4',
    description: 'Identity management',
    estimatedCost: { min: 0, max: 500 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_user_assigned_identity',
      defaultConfig: {
        name: 'app-identity',
      },
    },
  },
  {
    id: 'azure-key-vault',
    serviceType: 'paas',
    name: 'Azure Key Vault',
    category: 'security',
    provider: 'azure',
    icon: Key,
    color: '#0078D4',
    description: 'Secret management',
    estimatedCost: { min: 0, max: 50 },
    terraform: {
      provider: 'azure',
      resource: 'azurerm_key_vault',
      defaultConfig: {
        sku_name: 'standard',
        soft_delete_retention_days: 90,
        purge_protection_enabled: true,
        enable_rbac_authorization: true,
      },
    },
  },

  // DevOps & CI/CD Tools
  {
    id: 'docker',
    serviceType: 'iaas',
    name: 'Docker Container',
    category: 'devops',
    provider: 'generic',
    generatorType: 'docker',
    icon: Container,
    color: '#2496ED',
    description: 'Containerized application — generates a docker-compose service entry',
    estimatedCost: { min: 0, max: 0 },
  },
  {
    id: 'terraform',
    serviceType: 'generic',
    name: 'Terraform',
    category: 'devops',
    provider: 'generic',
    generatorType: 'documentation',
    icon: FileCode,
    color: '#7B42BC',
    description:
      'Infrastructure as Code annotation — architectural reference node; all cloud components already generate Terraform',
    estimatedCost: { min: 0, max: 0 },
  },
  {
    id: 'ansible',
    serviceType: 'generic',
    name: 'Ansible',
    category: 'devops',
    provider: 'generic',
    generatorType: 'documentation',
    icon: Terminal,
    color: '#EE0000',
    description:
      'Configuration management annotation — documents that Ansible manages this part of the infrastructure',
    estimatedCost: { min: 0, max: 0 },
  },
  {
    id: 'jenkins',
    serviceType: 'generic',
    name: 'Jenkins',
    category: 'devops',
    provider: 'generic',
    generatorType: 'cicd',
    icon: Cog,
    color: '#D24939',
    description: 'CI/CD automation server — generates a Jenkinsfile pipeline definition',
    estimatedCost: { min: 0, max: 100 },
    cicd: {
      tool: 'jenkins',
      defaultConfig: {
        triggers: ['pollSCM'],
        branches: ['main'],
        runsOn: 'any',
        stages: ['Checkout', 'Build', 'Test', 'Docker Build', 'Deploy'],
        deployTarget: 'kubernetes',
      },
    },
  },
  {
    id: 'github-actions',
    serviceType: 'generic',
    name: 'GitHub Actions',
    category: 'devops',
    provider: 'generic',
    generatorType: 'cicd',
    icon: GitBranch,
    color: '#2088FF',
    description: 'CI/CD workflow automation — generates .github/workflows/deploy.yml',
    estimatedCost: { min: 0, max: 100 },
    cicd: {
      tool: 'github-actions',
      defaultConfig: {
        triggers: ['push', 'pull_request'],
        branches: ['main'],
        runsOn: 'ubuntu-latest',
        stages: ['build', 'test', 'deploy'],
        nodeVersion: '20',
        deployTarget: 'kubernetes',
      },
    },
  },
  {
    id: 'gitlab-ci',
    serviceType: 'generic',
    name: 'GitLab CI/CD',
    category: 'devops',
    provider: 'generic',
    generatorType: 'cicd',
    icon: GitBranch,
    color: '#FC6D26',
    description: 'Built-in CI/CD pipelines — generates .gitlab-ci.yml',
    estimatedCost: { min: 0, max: 100 },
    cicd: {
      tool: 'gitlab-ci',
      defaultConfig: {
        triggers: ['push', 'merge_request'],
        branches: ['main', 'develop'],
        runsOn: 'docker',
        stages: ['build', 'test', 'deploy'],
        deployTarget: 'kubernetes',
      },
    },
  },
  {
    id: 'argocd',
    serviceType: 'generic',
    name: 'ArgoCD',
    category: 'devops',
    provider: 'generic',
    generatorType: 'kubernetes',
    icon: Workflow,
    color: '#EF7B4D',
    description: 'GitOps continuous delivery — generates an ArgoCD Application manifest',
    estimatedCost: { min: 0, max: 0 },
    cicd: {
      tool: 'argocd',
      defaultConfig: {
        repoUrl: 'https://github.com/org/repo',
        targetRevision: 'HEAD',
        appNamespace: 'argocd',
        destinationNamespace: 'default',
        syncPolicy: 'automated',
        selfHeal: true,
        prune: true,
      },
    },
  },
  {
    id: 'helm',
    name: 'Helm Chart',
    category: 'devops',
    provider: 'generic',
    generatorType: 'kubernetes',
    icon: Package,
    color: '#0F1689',
    description: 'Kubernetes package manager — generates a Helm values.yaml',
    estimatedCost: { min: 0, max: 0 },
    cicd: {
      tool: 'helm',
      defaultConfig: {
        chartName: 'my-app',
        chartVersion: '1.0.0',
        replicaCount: 1,
        imageRepository: 'my-registry/my-app',
        imageTag: 'latest',
        serviceType: 'ClusterIP',
        ingressEnabled: false,
      },
    },
  },

  // Monitoring & Observability
  {
    id: 'prometheus',
    serviceType: 'saas',
    name: 'Prometheus',
    category: 'analytics',
    provider: 'generic',
    generatorType: 'monitoring',
    icon: Gauge,
    color: '#E6522C',
    description: 'Metrics monitoring — generates prometheus.yml scrape config',
    estimatedCost: { min: 0, max: 100 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        scrapeInterval: '15s',
        evaluationInterval: '15s',
        retentionTime: '15d',
        port: 9090,
      },
    },
  },
  {
    id: 'grafana',
    serviceType: 'saas',
    name: 'Grafana',
    category: 'analytics',
    provider: 'generic',
    generatorType: 'monitoring',
    icon: BarChart,
    color: '#F46800',
    description: 'Visualization dashboards — documents Grafana datasource and dashboard config',
    estimatedCost: { min: 0, max: 100 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        datasource: 'prometheus',
        port: 3000,
        adminUser: 'admin',
        authAnonymousEnabled: false,
      },
    },
  },
  {
    id: 'datadog',
    serviceType: 'saas',
    name: 'Datadog',
    category: 'analytics',
    provider: 'generic',
    generatorType: 'monitoring',
    icon: Activity,
    color: '#632CA6',
    description: 'Cloud monitoring platform — generates Datadog agent configuration',
    estimatedCost: { min: 15, max: 500 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        site: 'datadoghq.com',
        env: 'production',
        service: 'my-app',
        logLevel: 'info',
        apmEnabled: true,
        logsEnabled: true,
        processAgentEnabled: false,
      },
    },
  },
  {
    id: 'elastic-stack',
    serviceType: 'saas',
    name: 'ELK Stack',
    category: 'analytics',
    provider: 'generic',
    generatorType: 'monitoring',
    icon: Search,
    color: '#005571',
    description: 'Log aggregation & search — documents Elasticsearch/Logstash/Kibana setup',
    estimatedCost: { min: 0, max: 500 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        elasticsearchPort: 9200,
        kibanaPort: 5601,
        logstashPort: 5044,
        heapSize: '1g',
        indices: ['app-logs-*', 'nginx-access-*'],
      },
    },
  },
  {
    id: 'newrelic',
    serviceType: 'saas',
    name: 'New Relic',
    category: 'analytics',
    provider: 'generic',
    generatorType: 'monitoring',
    icon: Eye,
    color: '#008C99',
    description: 'Application performance monitoring — documents New Relic agent configuration',
    estimatedCost: { min: 0, max: 300 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        appName: 'my-app',
        licenseKey: '${NEW_RELIC_LICENSE_KEY}',
        distributedTracingEnabled: true,
        logLevel: 'info',
      },
    },
  },
  {
    id: 'jaeger',
    serviceType: 'saas',
    name: 'Jaeger',
    category: 'analytics',
    provider: 'generic',
    generatorType: 'monitoring',
    icon: Activity,
    color: '#60D0E4',
    description: 'Distributed tracing — documents Jaeger collector and UI configuration',
    estimatedCost: { min: 0, max: 0 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        collectorPort: 14268,
        queryPort: 16686,
        samplingType: 'probabilistic',
        samplingParam: 0.1,
        storageType: 'memory',
      },
    },
  },

  // Messaging & Queues
  {
    id: 'rabbitmq',
    serviceType: 'paas',
    name: 'RabbitMQ',
    category: 'service',
    provider: 'generic',
    generatorType: 'docker',
    icon: MessageSquare,
    color: '#FF6600',
    description: 'Message broker — generates a docker-compose or K8s manifest entry',
    estimatedCost: { min: 0, max: 200 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        defaultUser: 'admin',
        defaultPass: '${RABBITMQ_PASSWORD}',
        managementPort: 15672,
        amqpPort: 5672,
        vhost: '/',
        replicaCount: 1,
      },
    },
  },
  {
    id: 'kafka',
    serviceType: 'paas',
    name: 'Apache Kafka',
    category: 'service',
    provider: 'generic',
    generatorType: 'docker',
    icon: Activity,
    color: '#231F20',
    description: 'Event streaming platform — generates a docker-compose or K8s manifest entry',
    estimatedCost: { min: 50, max: 1000 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        brokerId: 1,
        port: 9092,
        partitions: 3,
        replicationFactor: 1,
        retentionHours: 168,
        zookeeperConnect: 'zookeeper:2181',
      },
    },
  },
  {
    id: 'nats',
    serviceType: 'paas',
    name: 'NATS',
    category: 'service',
    provider: 'generic',
    generatorType: 'docker',
    icon: Wifi,
    color: '#27AAE1',
    description: 'Cloud native messaging — generates a docker-compose entry',
    estimatedCost: { min: 0, max: 100 },
    cicd: {
      tool: 'generic',
      defaultConfig: {
        port: 4222,
        monitorPort: 8222,
        clusterPort: 6222,
        jetStreamEnabled: true,
      },
    },
  },

  // Security Services
  {
    id: 'vault',
    serviceType: 'paas',
    name: 'HashiCorp Vault',
    category: 'security',
    provider: 'generic',
    generatorType: 'documentation',
    icon: Lock,
    color: '#000000',
    description:
      'Secrets management — architectural annotation; secrets should be provided via environment variables',
    estimatedCost: { min: 0, max: 100 },
  },
  {
    id: 'oauth-provider',
    serviceType: 'paas',
    name: 'OAuth Provider',
    category: 'security',
    provider: 'generic',
    icon: Key,
    color: '#EB5424',
    description: 'Authentication provider',
    estimatedCost: { min: 0, max: 100 },
  },
  {
    id: 'waf',
    serviceType: 'paas',
    name: 'Web Application Firewall',
    category: 'security',
    provider: 'generic',
    icon: Shield,
    color: '#FF4444',
    description: 'Web security protection',
    estimatedCost: { min: 5, max: 500 },
  },

  // Cloudflare Services
  {
    id: 'cloudflare-cdn',
    serviceType: 'iaas',
    name: 'Cloudflare CDN',
    category: 'service',
    provider: 'cloudflare',
    icon: Globe,
    color: '#F38020',
    description: 'Global content delivery',
    estimatedCost: { min: 0, max: 200 },
  },
  {
    id: 'cloudflare-pages',
    serviceType: 'hosting',
    name: 'Cloudflare Pages',
    category: 'frontend',
    provider: 'cloudflare',
    icon: Code,
    color: '#F38020',
    description: 'JAMstack platform',
    estimatedCost: { min: 0, max: 20 },
  },
  {
    id: 'cloudflare-r2',
    serviceType: 'paas',
    name: 'Cloudflare R2',
    category: 'cloud',
    provider: 'cloudflare',
    icon: HardDrive,
    color: '#F38020',
    description: 'S3-compatible object storage',
    estimatedCost: { min: 0, max: 100 },
  },
  {
    id: 'cloudflare-d1',
    name: 'Cloudflare D1',
    category: 'database',
    provider: 'cloudflare',
    icon: Database,
    color: '#F38020',
    description: 'Serverless SQLite',
    estimatedCost: { min: 0, max: 50 },
  },

  // Other Popular Services
  {
    id: 'stripe',
    name: 'Stripe Payments',
    category: 'service',
    provider: 'generic',
    icon: ShoppingCart,
    color: '#635BFF',
    description: 'Payment processing',
    estimatedCost: { min: 0, max: 0 },
  },
  {
    id: 'twilio',
    name: 'Twilio',
    category: 'service',
    provider: 'generic',
    icon: Smartphone,
    color: '#F22F46',
    description: 'Communication APIs',
    estimatedCost: { min: 0, max: 200 },
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    category: 'service',
    provider: 'generic',
    icon: Mail,
    color: '#1A82E2',
    description: 'Email delivery service',
    estimatedCost: { min: 0, max: 100 },
  },
  {
    id: 'algolia',
    name: 'Algolia',
    category: 'service',
    provider: 'generic',
    icon: Search,
    color: '#5468FF',
    description: 'Search as a service',
    estimatedCost: { min: 0, max: 500 },
  },
  {
    id: 'nginx',
    name: 'NGINX',
    category: 'backend',
    provider: 'generic',
    icon: Server,
    color: '#009639',
    description: 'Web server / reverse proxy',
    estimatedCost: { min: 0, max: 0 },
  },
  {
    id: 'traefik',
    name: 'Traefik',
    category: 'backend',
    provider: 'generic',
    icon: Network,
    color: '#24A1C1',
    description: 'Cloud-native proxy',
    estimatedCost: { min: 0, max: 0 },
  },
]

// O(1) lookup map — built once at module load instead of O(n) linear scan per call
const CATALOG_MAP = new Map<string, ComponentConfig>(COMPONENT_CATALOG.map(c => [c.id, c]))

export function getComponentById(id: string): ComponentConfig | undefined {
  return CATALOG_MAP.get(id)
}

/**
 * Returns the effective generator type for a component.
 * - If a component has a `terraform` field → 'terraform' (even if generatorType is unset)
 * - Otherwise uses the explicit `generatorType` field
 * - Falls back to 'documentation' for unknown/unclassified components
 *
 * This means AWS/Azure/GCP cloud components don't need an explicit generatorType field:
 * their `terraform` field is authoritative.
 */
export function getEffectiveGeneratorType(component: ComponentConfig): GeneratorType {
  if (component.terraform) return 'terraform'
  return component.generatorType || 'documentation'
}

/** Human-readable label + color for each generator type — used in UI badges */
export const GENERATOR_TYPE_META: Record<
  GeneratorType,
  { label: string; color: string; bgColor: string }
> = {
  terraform: {
    label: 'Terraform',
    color: '#7B42BC',
    bgColor: 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300',
  },
  cicd: {
    label: 'CI/CD',
    color: '#2088FF',
    bgColor: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
  },
  kubernetes: {
    label: 'Kubernetes',
    color: '#326CE5',
    bgColor: 'bg-sky-100 text-sky-800 dark:bg-sky-900/30 dark:text-sky-300',
  },
  docker: {
    label: 'Docker',
    color: '#2496ED',
    bgColor: 'bg-cyan-100 text-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-300',
  },
  monitoring: {
    label: 'Monitoring',
    color: '#E6522C',
    bgColor: 'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300',
  },
  documentation: {
    label: 'Annotation',
    color: '#6B7280',
    bgColor: 'bg-gray-100 text-gray-600 dark:bg-gray-800/50 dark:text-gray-400',
  },
}

export function getComponentsByCategory(category: ComponentConfig['category']): ComponentConfig[] {
  return COMPONENT_CATALOG.filter(c => c.category === category)
}

export function getComponentsByProvider(provider: ComponentConfig['provider']): ComponentConfig[] {
  return COMPONENT_CATALOG.filter(c => c.provider === provider)
}

export function searchComponents(query: string): ComponentConfig[] {
  const lowerQuery = query.toLowerCase()
  return COMPONENT_CATALOG.filter(
    c =>
      c.name.toLowerCase().includes(lowerQuery) ||
      c.description.toLowerCase().includes(lowerQuery) ||
      c.category.toLowerCase().includes(lowerQuery) ||
      (c.provider && c.provider.toLowerCase().includes(lowerQuery))
  )
}

export const CATEGORIES = [
  { id: 'frontend', name: 'Frontend', icon: Code },
  { id: 'backend', name: 'Backend', icon: Server },
  { id: 'database', name: 'Databases', icon: Database },
  { id: 'cloud', name: 'Cloud Services', icon: Cloud },
  { id: 'service', name: 'Services', icon: Zap },
  { id: 'devops', name: 'DevOps & CI/CD', icon: GitBranch },
  { id: 'security', name: 'Security', icon: Shield },
  { id: 'analytics', name: 'Analytics & Monitoring', icon: BarChart },
] as const

export const PROVIDERS = [
  { id: 'aws', name: 'AWS', color: '#FF9900' },
  { id: 'gcp', name: 'Google Cloud', color: '#4285F4' },
  { id: 'azure', name: 'Microsoft Azure', color: '#0078D4' },
  { id: 'cloudflare', name: 'Cloudflare', color: '#F38020' },
  { id: 'vercel', name: 'Vercel', color: '#000000' },
  { id: 'generic', name: 'Multi-Cloud / Generic', color: '#6B7280' },
] as const

export type ValidComponentId = (typeof COMPONENT_CATALOG)[number]['id']
