export const APP_CONFIG = {
  name: 'JobStack',
  description: 'Find your perfect job in one place',
  url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  version: '0.1.0',
} as const;

export const PLANS = {
  FREE: {
    candidate: {
      savedJobs: 5,
      emailAlerts: 'basic',
      price: 0,
    },
    employer: {
      jobsPerMonth: 1,
      displayDays: 7,
      apiAccess: false,
      price: 0,
    },
  },
  PREMIUM_CANDIDATE: {
    savedJobs: Infinity,
    emailAlerts: 'instant',
    cvBuilder: true,
    noAds: true,
    price: 5,
  },
  PREMIUM_EMPLOYER: {
    jobsPerMonth: Infinity,
    displayDays: 30,
    apiAccess: true,
    apiRequestsPerMonth: 10000,
    featured: true,
    analytics: true,
    price: 49,
  },
  ENTERPRISE: {
    jobsPerMonth: Infinity,
    displayDays: 60,
    apiAccess: true,
    apiRequestsPerMonth: Infinity,
    featured: true,
    analytics: true,
    whiteLabel: true,
    support: 'priority',
    price: 199,
  },
} as const;

export const JOB_SOURCES = [
  'justjoinit',
  'nofluffjobs',
  'pracuj',
  'indeed',
  'native',
] as const;

// ============================================================================
// COMPREHENSIVE TECH STACKS - All modern technologies used in 2024/2025
// ============================================================================

export const TECH_STACKS = [
  // === Frontend Languages & Frameworks ===
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Vue.js',
  'Nuxt.js',
  'Angular',
  'Svelte',
  'SvelteKit',
  'Astro',
  'Remix',
  'Solid.js',
  'Qwik',
  'HTML5',
  'CSS3',
  'SCSS/Sass',
  'Less',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Chakra UI',
  'Ant Design',
  'Styled Components',
  'Emotion',
  'Framer Motion',

  // === Backend Languages & Frameworks ===
  'Node.js',
  'Express.js',
  'Fastify',
  'NestJS',
  'Hono',
  'Bun',
  'Deno',
  'Python',
  'Django',
  'Flask',
  'FastAPI',
  'Celery',
  'Java',
  'Spring Boot',
  'Spring Cloud',
  'Quarkus',
  'Micronaut',
  'Kotlin',
  'Ktor',
  'C#',
  '.NET',
  '.NET Core',
  'ASP.NET',
  'Blazor',
  'PHP',
  'Laravel',
  'Symfony',
  'Ruby',
  'Ruby on Rails',
  'Sinatra',
  'Go',
  'Gin',
  'Echo',
  'Fiber',
  'Rust',
  'Actix',
  'Axum',
  'Tokio',
  'Scala',
  'Akka',
  'Play Framework',
  'Elixir',
  'Phoenix',
  'Clojure',
  'Haskell',
  'F#',
  'Erlang',

  // === Mobile Development ===
  'React Native',
  'Flutter',
  'Dart',
  'Swift',
  'SwiftUI',
  'Objective-C',
  'Kotlin',
  'Jetpack Compose',
  'iOS',
  'Android',
  'Expo',
  'Ionic',
  'Capacitor',
  'Xamarin',
  'MAUI',

  // === Databases - SQL ===
  'PostgreSQL',
  'MySQL',
  'MariaDB',
  'SQL Server',
  'Oracle DB',
  'SQLite',
  'CockroachDB',
  'TimescaleDB',
  'Supabase',
  'PlanetScale',
  'Neon',

  // === Databases - NoSQL ===
  'MongoDB',
  'Redis',
  'Cassandra',
  'DynamoDB',
  'Couchbase',
  'CouchDB',
  'Neo4j',
  'ArangoDB',
  'InfluxDB',
  'Elasticsearch',
  'OpenSearch',
  'Memcached',
  'ScyllaDB',
  'FaunaDB',

  // === Cloud Platforms ===
  'AWS',
  'Azure',
  'GCP',
  'DigitalOcean',
  'Linode',
  'Vultr',
  'Hetzner',
  'OVH',
  'Oracle Cloud',
  'IBM Cloud',
  'Alibaba Cloud',
  'Cloudflare',
  'Vercel',
  'Netlify',
  'Railway',
  'Render',
  'Fly.io',
  'Heroku',

  // === AWS Services ===
  'AWS Lambda',
  'AWS EC2',
  'AWS S3',
  'AWS RDS',
  'AWS ECS',
  'AWS EKS',
  'AWS Fargate',
  'AWS CloudFormation',
  'AWS CDK',
  'AWS API Gateway',
  'AWS SQS',
  'AWS SNS',
  'AWS Kinesis',
  'AWS DynamoDB',
  'AWS Cognito',
  'AWS IAM',
  'AWS CloudWatch',
  'AWS Step Functions',
  'AWS EventBridge',

  // === Azure Services ===
  'Azure Functions',
  'Azure App Service',
  'Azure AKS',
  'Azure DevOps',
  'Azure Blob Storage',
  'Azure Cosmos DB',
  'Azure SQL',
  'Azure Service Bus',
  'Azure Event Hub',
  'Azure AD',
  'Azure Container Apps',

  // === GCP Services ===
  'Google Cloud Run',
  'Google Cloud Functions',
  'GKE',
  'BigQuery',
  'Cloud Pub/Sub',
  'Cloud Storage',
  'Firestore',
  'Firebase',
  'Cloud SQL',
  'Cloud Spanner',

  // === DevOps & Infrastructure ===
  'Docker',
  'Kubernetes',
  'Helm',
  'OpenShift',
  'Rancher',
  'Podman',
  'containerd',
  'Docker Compose',
  'Docker Swarm',

  // === IaC (Infrastructure as Code) ===
  'Terraform',
  'Pulumi',
  'Ansible',
  'Chef',
  'Puppet',
  'SaltStack',
  'CloudFormation',
  'Crossplane',
  'Terragrunt',
  'OpenTofu',

  // === CI/CD ===
  'GitHub Actions',
  'GitLab CI',
  'Jenkins',
  'CircleCI',
  'Travis CI',
  'Azure Pipelines',
  'Bitbucket Pipelines',
  'ArgoCD',
  'Flux',
  'Spinnaker',
  'Tekton',
  'Drone CI',
  'TeamCity',
  'Bamboo',

  // === Monitoring & Observability ===
  'Prometheus',
  'Grafana',
  'Datadog',
  'New Relic',
  'Splunk',
  'ELK Stack',
  'Elasticsearch',
  'Logstash',
  'Kibana',
  'Loki',
  'Jaeger',
  'Zipkin',
  'OpenTelemetry',
  'Sentry',
  'PagerDuty',
  'VictoriaMetrics',
  'Thanos',
  'Mimir',
  'Tempo',

  // === Networking & Security ===
  'Nginx',
  'Apache',
  'HAProxy',
  'Traefik',
  'Envoy',
  'Istio',
  'Linkerd',
  'Kong',
  'Consul',
  'Vault',
  'Cert-Manager',
  'Let\'s Encrypt',
  'Cloudflare',
  'WAF',
  'OAuth 2.0',
  'OpenID Connect',
  'SAML',
  'JWT',
  'Keycloak',
  'Auth0',
  'Okta',

  // === Message Queues & Streaming ===
  'Kafka',
  'RabbitMQ',
  'Apache Pulsar',
  'NATS',
  'ActiveMQ',
  'Amazon SQS',
  'Amazon Kinesis',
  'Google Pub/Sub',
  'Azure Service Bus',
  'Redis Streams',
  'Apache Flink',
  'Apache Spark',
  'Apache Storm',
  'Debezium',

  // === API & Communication ===
  'REST API',
  'GraphQL',
  'gRPC',
  'WebSocket',
  'Socket.io',
  'Apollo GraphQL',
  'Hasura',
  'tRPC',
  'OpenAPI',
  'Swagger',
  'Postman',
  'Insomnia',
  'MQTT',
  'AMQP',
  'Protocol Buffers',

  // === Testing ===
  'Jest',
  'Vitest',
  'Mocha',
  'Chai',
  'Cypress',
  'Playwright',
  'Selenium',
  'Puppeteer',
  'Testing Library',
  'Enzyme',
  'PyTest',
  'unittest',
  'JUnit',
  'Mockito',
  'xUnit',
  'NUnit',
  'RSpec',
  'PHPUnit',
  'k6',
  'Gatling',
  'JMeter',
  'Locust',
  'Artillery',

  // === Version Control & Collaboration ===
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'Azure Repos',
  'SVN',
  'Mercurial',

  // === AI/ML & Data Science ===
  'TensorFlow',
  'PyTorch',
  'Keras',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'SciPy',
  'Jupyter',
  'OpenCV',
  'NLTK',
  'spaCy',
  'Hugging Face',
  'LangChain',
  'OpenAI API',
  'Anthropic Claude',
  'MLflow',
  'Kubeflow',
  'Ray',
  'Weights & Biases',
  'DVC',
  'Apache Airflow',
  'dbt',
  'Snowflake',
  'Databricks',
  'Apache Spark',
  'Hadoop',
  'Presto',
  'Trino',

  // === CMS & Headless CMS ===
  'WordPress',
  'Drupal',
  'Strapi',
  'Contentful',
  'Sanity',
  'Prismic',
  'Ghost',
  'Directus',
  'Payload CMS',
  'KeystoneJS',

  // === E-commerce ===
  'Shopify',
  'Magento',
  'WooCommerce',
  'BigCommerce',
  'Medusa',
  'Saleor',
  'Stripe',
  'PayPal',

  // === Low-Code / No-Code ===
  'Retool',
  'Appsmith',
  'Budibase',
  'Tooljet',
  'n8n',
  'Zapier',
  'Make (Integromat)',
  'Power Automate',

  // === Other Tools ===
  'Linux',
  'Ubuntu',
  'Debian',
  'RHEL',
  'CentOS',
  'Alpine Linux',
  'Windows Server',
  'macOS',
  'Bash',
  'Shell Scripting',
  'PowerShell',
  'Vim',
  'VS Code',
  'IntelliJ IDEA',
  'WebStorm',
  'PyCharm',
  'Jira',
  'Confluence',
  'Slack',
  'Notion',
  'Figma',
  'Storybook',
  'Chromatic',
  'LaunchDarkly',
  'Feature Flags',
] as const;

// ============================================================================
// JOB ROLES - Comprehensive IT job categories with popular tech stacks
// ============================================================================

export const JOB_ROLES = {
  // === Development ===
  'Frontend Developer': {
    icon: '🎨',
    category: 'development',
    stacks: ['JavaScript', 'TypeScript', 'React', 'Next.js', 'Vue.js', 'Angular', 'Svelte', 'Tailwind CSS', 'HTML5', 'CSS3'],
  },
  'Backend Developer': {
    icon: '⚙️',
    category: 'development',
    stacks: ['Node.js', 'Python', 'Java', 'Go', 'C#', '.NET', 'PHP', 'Ruby', 'PostgreSQL', 'MongoDB', 'REST API'],
  },
  'Fullstack Developer': {
    icon: '🔄',
    category: 'development',
    stacks: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Next.js', 'PostgreSQL', 'MongoDB', 'Docker', 'GraphQL'],
  },
  'Software Engineer': {
    icon: '💻',
    category: 'development',
    stacks: ['Java', 'Python', 'C++', 'Go', 'Rust', 'PostgreSQL', 'Docker', 'Kubernetes', 'Git', 'Linux'],
  },
  'Software Architect': {
    icon: '🏛️',
    category: 'development',
    stacks: ['AWS', 'Azure', 'GCP', 'Kubernetes', 'Docker', 'Microservices', 'Kafka', 'PostgreSQL', 'Redis'],
  },
  'Tech Lead': {
    icon: '👑',
    category: 'development',
    stacks: ['JavaScript', 'TypeScript', 'Python', 'AWS', 'Docker', 'Kubernetes', 'PostgreSQL', 'Git', 'Agile'],
  },
  'Principal Engineer': {
    icon: '🎖️',
    category: 'development',
    stacks: ['AWS', 'Azure', 'Kubernetes', 'Docker', 'Python', 'Go', 'PostgreSQL', 'Kafka', 'Microservices'],
  },
  'Engineering Manager': {
    icon: '📋',
    category: 'development',
    stacks: ['Agile', 'Scrum', 'Jira', 'Git', 'AWS', 'Python', 'JavaScript', 'Docker'],
  },

  // === Mobile Development ===
  'Mobile Developer': {
    icon: '📱',
    category: 'mobile',
    stacks: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'iOS', 'Android', 'TypeScript', 'Firebase'],
  },
  'iOS Developer': {
    icon: '🍎',
    category: 'mobile',
    stacks: ['Swift', 'SwiftUI', 'Objective-C', 'iOS', 'Xcode', 'Core Data', 'UIKit', 'Combine'],
  },
  'Android Developer': {
    icon: '🤖',
    category: 'mobile',
    stacks: ['Kotlin', 'Java', 'Android', 'Jetpack Compose', 'Android Studio', 'Firebase', 'Room', 'Retrofit'],
  },
  'Flutter Developer': {
    icon: '🦋',
    category: 'mobile',
    stacks: ['Flutter', 'Dart', 'Firebase', 'iOS', 'Android', 'REST API', 'Bloc', 'Provider'],
  },
  'React Native Developer': {
    icon: '⚛️',
    category: 'mobile',
    stacks: ['React Native', 'TypeScript', 'JavaScript', 'Expo', 'Redux', 'Firebase', 'iOS', 'Android'],
  },

  // === DevOps & Infrastructure ===
  'DevOps Engineer': {
    icon: '🚀',
    category: 'devops',
    stacks: ['Docker', 'Kubernetes', 'AWS', 'Azure', 'GCP', 'Terraform', 'Ansible', 'Jenkins', 'GitLab CI', 'Linux'],
  },
  'Cloud Engineer': {
    icon: '☁️',
    category: 'devops',
    stacks: ['AWS', 'Azure', 'GCP', 'Terraform', 'Kubernetes', 'Docker', 'CloudFormation', 'Pulumi', 'Linux'],
  },
  'Platform Engineer': {
    icon: '🏗️',
    category: 'devops',
    stacks: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'Azure', 'Prometheus', 'Grafana', 'ArgoCD', 'Helm', 'Go'],
  },
  'SRE (Site Reliability Engineer)': {
    icon: '🛡️',
    category: 'devops',
    stacks: ['Kubernetes', 'Docker', 'Prometheus', 'Grafana', 'AWS', 'Python', 'Go', 'Linux', 'Datadog', 'Terraform'],
  },
  'Infrastructure Engineer': {
    icon: '🔧',
    category: 'devops',
    stacks: ['AWS', 'Azure', 'Terraform', 'Ansible', 'Linux', 'Docker', 'Kubernetes', 'Networking', 'Bash'],
  },
  'Systems Administrator': {
    icon: '🖥️',
    category: 'devops',
    stacks: ['Linux', 'Windows Server', 'Bash', 'PowerShell', 'Docker', 'Ansible', 'VMware', 'Networking'],
  },
  'Network Engineer': {
    icon: '🌐',
    category: 'devops',
    stacks: ['Cisco', 'Juniper', 'Networking', 'TCP/IP', 'DNS', 'VPN', 'Firewall', 'Load Balancing', 'SDN'],
  },
  'Cloud Architect': {
    icon: '🏰',
    category: 'devops',
    stacks: ['AWS', 'Azure', 'GCP', 'Terraform', 'Kubernetes', 'Microservices', 'Serverless', 'Security'],
  },
  'Release Engineer': {
    icon: '�',
    category: 'devops',
    stacks: ['Jenkins', 'GitLab CI', 'GitHub Actions', 'Docker', 'Kubernetes', 'ArgoCD', 'Helm', 'Git'],
  },

  // === Data & Analytics ===
  'Data Engineer': {
    icon: '�📊',
    category: 'data',
    stacks: ['Python', 'SQL', 'Apache Spark', 'Apache Airflow', 'AWS', 'Kafka', 'dbt', 'Snowflake', 'Databricks'],
  },
  'Data Scientist': {
    icon: '🔬',
    category: 'data',
    stacks: ['Python', 'Pandas', 'NumPy', 'Scikit-learn', 'TensorFlow', 'PyTorch', 'SQL', 'Jupyter', 'R'],
  },
  'Data Analyst': {
    icon: '📈',
    category: 'data',
    stacks: ['SQL', 'Python', 'Excel', 'Tableau', 'Power BI', 'Looker', 'Google Analytics', 'Metabase'],
  },
  'Business Intelligence': {
    icon: '💹',
    category: 'data',
    stacks: ['SQL', 'Tableau', 'Power BI', 'Looker', 'Metabase', 'Excel', 'Python', 'dbt'],
  },
  'Machine Learning Engineer': {
    icon: '🤖',
    category: 'data',
    stacks: ['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'MLflow', 'Kubeflow', 'AWS', 'Docker', 'Kubernetes'],
  },
  'AI Engineer': {
    icon: '🧠',
    category: 'data',
    stacks: ['Python', 'PyTorch', 'TensorFlow', 'LangChain', 'OpenAI API', 'Hugging Face', 'Vector DBs', 'RAG'],
  },
  'MLOps Engineer': {
    icon: '⚡',
    category: 'data',
    stacks: ['Python', 'MLflow', 'Kubeflow', 'Docker', 'Kubernetes', 'AWS', 'Terraform', 'Airflow', 'DVC'],
  },
  'NLP Engineer': {
    icon: '💬',
    category: 'data',
    stacks: ['Python', 'spaCy', 'NLTK', 'Hugging Face', 'Transformers', 'PyTorch', 'TensorFlow', 'LangChain'],
  },
  'Computer Vision Engineer': {
    icon: '👁️',
    category: 'data',
    stacks: ['Python', 'OpenCV', 'PyTorch', 'TensorFlow', 'YOLO', 'CNNs', 'AWS', 'Docker'],
  },
  'Analytics Engineer': {
    icon: '📐',
    category: 'data',
    stacks: ['SQL', 'dbt', 'Python', 'Snowflake', 'BigQuery', 'Looker', 'Airflow', 'Git'],
  },

  // === Security ===
  'Security Engineer': {
    icon: '🔐',
    category: 'security',
    stacks: ['AWS', 'Azure', 'Kubernetes', 'Python', 'Linux', 'SIEM', 'Burp Suite', 'OWASP', 'Terraform'],
  },
  'Cybersecurity Analyst': {
    icon: '🛡️',
    category: 'security',
    stacks: ['SIEM', 'Splunk', 'Wireshark', 'Linux', 'Python', 'Firewall', 'IDS/IPS', 'Threat Intelligence'],
  },
  'Penetration Tester': {
    icon: '�',
    category: 'security',
    stacks: ['Kali Linux', 'Burp Suite', 'Metasploit', 'Python', 'OWASP', 'Nmap', 'Wireshark', 'SQL Injection'],
  },
  'DevSecOps Engineer': {
    icon: '🔒',
    category: 'security',
    stacks: ['Docker', 'Kubernetes', 'AWS', 'Terraform', 'Vault', 'SAST', 'DAST', 'Trivy', 'Snyk', 'SonarQube'],
  },
  'Cloud Security Engineer': {
    icon: '☁️🔐',
    category: 'security',
    stacks: ['AWS', 'Azure', 'GCP', 'Terraform', 'IAM', 'Vault', 'Kubernetes', 'SIEM', 'Compliance'],
  },
  'SOC Analyst': {
    icon: '📡',
    category: 'security',
    stacks: ['SIEM', 'Splunk', 'ELK Stack', 'Threat Intelligence', 'Incident Response', 'Python', 'Linux'],
  },

  // === QA & Testing ===
  'QA Engineer': {
    icon: '🧪',
    category: 'qa',
    stacks: ['Selenium', 'Cypress', 'Jest', 'Playwright', 'Python', 'JavaScript', 'Postman', 'JMeter', 'TestRail'],
  },
  'QA Automation Engineer': {
    icon: '��🧪',
    category: 'qa',
    stacks: ['Selenium', 'Cypress', 'Playwright', 'Python', 'Java', 'JavaScript', 'TestNG', 'Robot Framework'],
  },
  'SDET': {
    icon: '🔧🧪',
    category: 'qa',
    stacks: ['Python', 'Java', 'JavaScript', 'Selenium', 'Cypress', 'API Testing', 'Docker', 'CI/CD', 'Git'],
  },
  'Performance Engineer': {
    icon: '⚡🧪',
    category: 'qa',
    stacks: ['k6', 'JMeter', 'Gatling', 'Locust', 'Artillery', 'Python', 'Grafana', 'Prometheus'],
  },
  'Manual QA Tester': {
    icon: '✅',
    category: 'qa',
    stacks: ['TestRail', 'Jira', 'Postman', 'SQL', 'API Testing', 'Regression Testing', 'Bug Tracking'],
  },

  // === Product & Design ===
  'Product Manager': {
    icon: '📦',
    category: 'product',
    stacks: ['Jira', 'Confluence', 'Figma', 'Analytics', 'SQL', 'A/B Testing', 'Roadmapping', 'Agile'],
  },
  'Product Owner': {
    icon: '🎯',
    category: 'product',
    stacks: ['Jira', 'Confluence', 'Agile', 'Scrum', 'Stakeholder Management', 'User Stories', 'Backlog'],
  },
  'UI/UX Designer': {
    icon: '🎨',
    category: 'product',
    stacks: ['Figma', 'Sketch', 'Adobe XD', 'Prototyping', 'User Research', 'Design Systems', 'HTML/CSS'],
  },
  'UX Researcher': {
    icon: '🔍',
    category: 'product',
    stacks: ['User Interviews', 'Surveys', 'Usability Testing', 'Analytics', 'Figma', 'Miro', 'A/B Testing'],
  },
  'Scrum Master': {
    icon: '🏃',
    category: 'product',
    stacks: ['Scrum', 'Agile', 'Jira', 'Confluence', 'Kanban', 'Retrospectives', 'Sprint Planning'],
  },
  'Technical Product Manager': {
    icon: '⚙️📦',
    category: 'product',
    stacks: ['Jira', 'SQL', 'API', 'Technical Documentation', 'AWS', 'Agile', 'Roadmapping'],
  },

  // === Specialized Development ===
  'Blockchain Developer': {
    icon: '⛓️',
    category: 'specialized',
    stacks: ['Solidity', 'Ethereum', 'Web3.js', 'Hardhat', 'Smart Contracts', 'JavaScript', 'TypeScript', 'Rust'],
  },
  'Game Developer': {
    icon: '🎮',
    category: 'specialized',
    stacks: ['Unity', 'Unreal Engine', 'C#', 'C++', 'Godot', 'Game Design', 'OpenGL', 'DirectX'],
  },
  'Embedded Developer': {
    icon: '�',
    category: 'specialized',
    stacks: ['C', 'C++', 'Embedded Linux', 'RTOS', 'ARM', 'Microcontrollers', 'IoT', 'Firmware'],
  },
  'IoT Developer': {
    icon: '📡',
    category: 'specialized',
    stacks: ['Python', 'C', 'C++', 'MQTT', 'AWS IoT', 'Azure IoT', 'Raspberry Pi', 'Arduino', 'Edge Computing'],
  },
  'Firmware Engineer': {
    icon: '🔧',
    category: 'specialized',
    stacks: ['C', 'C++', 'Embedded Systems', 'RTOS', 'ARM', 'Microcontrollers', 'Debugging', 'Hardware'],
  },
  'Graphics Developer': {
    icon: '🖼️',
    category: 'specialized',
    stacks: ['OpenGL', 'Vulkan', 'DirectX', 'C++', 'GLSL', 'WebGL', 'Three.js', 'Shaders'],
  },
  'VR/AR Developer': {
    icon: '🥽',
    category: 'specialized',
    stacks: ['Unity', 'Unreal Engine', 'C#', 'C++', 'ARKit', 'ARCore', 'OpenXR', '3D Modeling'],
  },

  // === Support & Consulting ===
  'Technical Support Engineer': {
    icon: '🎧',
    category: 'support',
    stacks: ['Linux', 'Networking', 'Troubleshooting', 'Ticketing Systems', 'Cloud', 'Scripting'],
  },
  'Solutions Architect': {
    icon: '🏗️',
    category: 'support',
    stacks: ['AWS', 'Azure', 'GCP', 'Architecture Design', 'Microservices', 'Integration', 'Cloud Migration'],
  },
  'Technical Consultant': {
    icon: '💼',
    category: 'support',
    stacks: ['AWS', 'Azure', 'Architecture', 'DevOps', 'Cloud Migration', 'Technical Writing'],
  },
  'Pre-Sales Engineer': {
    icon: '🤝',
    category: 'support',
    stacks: ['Cloud', 'Technical Presentations', 'POC', 'Solution Design', 'Customer Engagement'],
  },

  // === Database ===
  'Database Administrator': {
    icon: '🗄️',
    category: 'database',
    stacks: ['PostgreSQL', 'MySQL', 'SQL Server', 'Oracle', 'MongoDB', 'Redis', 'Backup & Recovery', 'Performance Tuning'],
  },
  'Database Developer': {
    icon: '🗃️',
    category: 'database',
    stacks: ['SQL', 'PostgreSQL', 'MySQL', 'PL/SQL', 'T-SQL', 'Stored Procedures', 'ETL', 'Data Modeling'],
  },
} as const;

// Work modes
export const WORK_MODES = {
  remote: {
    label: 'Zdalnie',
    icon: '🏠',
    description: 'Praca w pełni zdalna z dowolnego miejsca',
  },
  hybrid: {
    label: 'Hybrydowo',
    icon: '🔄',
    description: 'Część czasu w biurze, część zdalnie',
  },
  onsite: {
    label: 'Stacjonarnie',
    icon: '🏢',
    description: 'Praca w biurze',
  },
} as const;

// Polish voivodeships
export const VOIVODESHIPS = [
  'dolnośląskie',
  'kujawsko-pomorskie',
  'lubelskie',
  'lubuskie',
  'łódzkie',
  'małopolskie',
  'mazowieckie',
  'opolskie',
  'podkarpackie',
  'podlaskie',
  'pomorskie',
  'śląskie',
  'świętokrzyskie',
  'warmińsko-mazurskie',
  'wielkopolskie',
  'zachodniopomorskie',
] as const;

// Distance options in km
export const DISTANCE_OPTIONS = [10, 25, 50, 100, 150] as const;

export const LOCATIONS = [
  'Warszawa',
  'Kraków',
  'Wrocław',
  'Poznań',
  'Gdańsk',
  'Łódź',
  'Katowice',
  'Szczecin',
  'Bydgoszcz',
  'Lublin',
] as const;
