export const APP_CONFIG = {
  name: 'JobStack',
  description: 'Find your perfect job in one place',
  url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  version: '0.1.0',
} as const;

export const PLANS = {
  FREE: {
    candidate: {
      savedJobs: 5,
      emailAlerts: 'basic',
      price: 0,
    },
    employer: {
      jobsPerMonth: 1,
      displayDays: 7,
      apiAccess: false,
      price: 0,
    },
  },
  PREMIUM_CANDIDATE: {
    savedJobs: Infinity,
    emailAlerts: 'instant',
    cvBuilder: true,
    noAds: true,
    price: 5,
  },
  PREMIUM_EMPLOYER: {
    jobsPerMonth: Infinity,
    displayDays: 30,
    apiAccess: true,
    apiRequestsPerMonth: 10000,
    featured: true,
    analytics: true,
    price: 49,
  },
  ENTERPRISE: {
    jobsPerMonth: Infinity,
    displayDays: 60,
    apiAccess: true,
    apiRequestsPerMonth: Infinity,
    featured: true,
    analytics: true,
    whiteLabel: true,
    support: 'priority',
    price: 199,
  },
} as const;

export const JOB_SOURCES = [
  'justjoinit',
  'nofluffjobs',
  'pracuj',
  'indeed',
  'native',
] as const;

export const TECH_STACKS = [
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Vue.js',
  'Angular',
  'Node.js',
  'Python',
  'Django',
  'Flask',
  'Java',
  'Spring',
  'C#',
  '.NET',
  'PHP',
  'Laravel',
  'Ruby',
  'Rails',
  'Go',
  'Rust',
  'Kotlin',
  'Swift',
  'Flutter',
  'React Native',
  'AWS',
  'Azure',
  'GCP',
  'Docker',
  'Kubernetes',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'GraphQL',
  'REST API',
] as const;

export const LOCATIONS = [
  'Warsaw',
  'Kraków',
  'Wrocław',
  'Poznań',
  'Gdańsk',
  'Łódź',
  'Katowice',
  'Szczecin',
  'Bydgoszcz',
  'Lublin',
  'Remote',
  'Hybrid',
] as const;
