/**
 * CI/CD Config Generator
 *
 * Converts CI/CD, Kubernetes, and monitoring nodes on the diagram canvas
 * into their respective configuration file formats:
 *
 *   github-actions  → .github/workflows/deploy.yml
 *   gitlab-ci       → .gitlab-ci.yml
 *   jenkins         → Jenkinsfile
 *   argocd          → argocd-app.yaml
 *   helm            → helm/values.yaml
 *   prometheus      → prometheus.yml
 *   datadog         → datadog.yaml
 *   rabbitmq/kafka  → docker-compose service entry
 *
 * Components that are 'documentation' or 'annotation' generate nothing —
 * the function returns null for them and the caller should inform the user.
 */

import { Node, Edge } from '@xyflow/react'
import { getComponentById, getEffectiveGeneratorType } from '@/lib/catalog'

export interface CICDOutput {
  filename: string
  content: string
  language: 'yaml' | 'groovy' | 'json' | 'bash'
  generatorType: string
  componentLabel: string
}

export interface CICDResult {
  outputs: CICDOutput[]
  skipped: { label: string; reason: string }[]
}

interface NodeData {
  label?: string
  componentId?: string
  component?: string
  config?: Record<string, any>
  [key: string]: unknown
}

// ─────────────────────────────────────────────
// GitHub Actions
// ─────────────────────────────────────────────
function generateGitHubActions(label: string, cfg: Record<string, any>): CICDOutput {
  const branches = (cfg.branches as string[] | undefined) || ['main']
  const triggers = (cfg.triggers as string[] | undefined) || ['push', 'pull_request']
  const runsOn = cfg.runsOn || 'ubuntu-latest'
  const nodeVersion = cfg.nodeVersion || '20'
  const deployTarget = cfg.deployTarget || 'kubernetes'

  const onSection = triggers.map((t: string) => {
    if (t === 'push') return `  push:\n    branches: [${branches.map((b: string) => `"${b}"`).join(', ')}]`
    if (t === 'pull_request') return `  pull_request:\n    branches: [${branches.map((b: string) => `"${b}"`).join(', ')}]`
    if (t === 'schedule') return `  schedule:\n    - cron: '0 2 * * *'`
    return `  ${t}: {}`
  }).join('\n')

  const deployStep = deployTarget === 'kubernetes'
    ? `      - name: Deploy to Kubernetes\n        run: kubectl apply -f k8s/`
    : deployTarget === 'ecs'
    ? `      - name: Deploy to ECS\n        run: aws ecs update-service --cluster production --service \${{ github.event.repository.name }} --force-new-deployment`
    : deployTarget === 'appservice'
    ? `      - name: Deploy to Azure App Service\n        uses: azure/webapps-deploy@v2\n        with:\n          app-name: \${{ vars.AZURE_APP_NAME }}`
    : deployTarget === 'lambda'
    ? `      - name: Deploy to Lambda\n        run: aws lambda update-function-code --function-name \${{ vars.LAMBDA_FUNCTION_NAME }} --zip-file fileb://function.zip`
    : `      - name: Deploy\n        run: echo "Configure deploy step"`

  const content = `# Generated by JobStack — ${label}
# Modify triggers, jobs, and steps to match your project requirements.
name: CI/CD Pipeline

on:
${onSection}

env:
  NODE_VERSION: '${nodeVersion}'

jobs:
  build:
    name: Build & Test
    runs-on: ${runsOn}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

  docker:
    name: Build & Push Docker Image
    runs-on: ${runsOn}
    needs: build
    if: github.ref == 'refs/heads/${branches[0]}'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: \${{ vars.DOCKER_REGISTRY }}
          username: \${{ secrets.REGISTRY_USERNAME }}
          password: \${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: \${{ vars.DOCKER_REGISTRY }}/\${{ github.event.repository.name }}:\${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ${runsOn}
    needs: docker
    if: github.ref == 'refs/heads/${branches[0]}'
    environment: production
    steps:
${deployStep}
`
  return {
    filename: '.github/workflows/deploy.yml',
    content,
    language: 'yaml',
    generatorType: 'cicd',
    componentLabel: label,
  }
}

// ─────────────────────────────────────────────
// GitLab CI/CD
// ─────────────────────────────────────────────
function generateGitLabCI(label: string, cfg: Record<string, any>): CICDOutput {
  const stages = (cfg.stages as string[] | undefined) || ['build', 'test', 'deploy']
  const branches = (cfg.branches as string[] | undefined) || ['main']

  const content = `# Generated by JobStack — ${label}
stages:${stages.map((s: string) => `\n  - ${s}`).join('')}

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

.default_rules: &default_rules
  rules:
    - if: '$CI_COMMIT_BRANCH == "${branches[0]}"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

build:
  stage: build
  image: node:20-alpine
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  <<: *default_rules

test:
  stage: test
  image: node:20-alpine
  needs: [build]
  script:
    - npm ci
    - npm run lint --if-present
    - npm test --if-present
  coverage: '/Lines\\s*:\\s*(\\d+\\.?\\d*)%/'
  <<: *default_rules

docker_build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  needs: [test]
  script:
    - docker login -u \$CI_REGISTRY_USER -p \$CI_REGISTRY_PASSWORD \$CI_REGISTRY
    - docker build -t \$CI_REGISTRY_IMAGE:\$CI_COMMIT_SHA .
    - docker push \$CI_REGISTRY_IMAGE:\$CI_COMMIT_SHA
  only:
    - ${branches[0]}

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  needs: [docker_build]
  script:
    - kubectl apply -f k8s/
    - kubectl rollout status deployment/\$CI_PROJECT_NAME
  environment:
    name: production
  only:
    - ${branches[0]}
`
  return {
    filename: '.gitlab-ci.yml',
    content,
    language: 'yaml',
    generatorType: 'cicd',
    componentLabel: label,
  }
}

// ─────────────────────────────────────────────
// Jenkinsfile (Declarative Pipeline)
// ─────────────────────────────────────────────
function generateJenkinsfile(label: string, cfg: Record<string, any>): CICDOutput {
  const stages = (cfg.stages as string[] | undefined) || ['Checkout', 'Build', 'Test', 'Docker Build', 'Deploy']
  const runsOn = cfg.runsOn || 'any'

  const stageBlocks = stages.map((s: string) => {
    if (s.toLowerCase() === 'checkout') {
      return `        stage('${s}') {\n            steps {\n                checkout scm\n            }\n        }`
    }
    if (s.toLowerCase() === 'build') {
      return `        stage('${s}') {\n            steps {\n                sh 'npm ci && npm run build'\n            }\n        }`
    }
    if (s.toLowerCase() === 'test') {
      return `        stage('${s}') {\n            steps {\n                sh 'npm test'\n            }\n            post {\n                always {\n                    junit 'test-results/**/*.xml'\n                }\n            }\n        }`
    }
    if (s.toLowerCase().includes('docker')) {
      return `        stage('${s}') {\n            steps {\n                script {\n                    docker.build("\${env.IMAGE_NAME}:\${env.BUILD_NUMBER}")\n                        .push()\n                }\n            }\n        }`
    }
    return `        stage('${s}') {\n            steps {\n                sh 'echo Running ${s}'\n            }\n        }`
  }).join('\n\n')

  const content = `// Generated by JobStack — ${label}
// Declarative Pipeline
pipeline {
    agent { label '${runsOn}' }

    environment {
        IMAGE_NAME = "\${env.JOB_NAME.toLowerCase()}"
        REGISTRY   = credentials('docker-registry-url')
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages {
${stageBlocks}
    }

    post {
        success {
            echo 'Pipeline succeeded!'
            // slackSend message: "Build \${env.BUILD_NUMBER} succeeded"
        }
        failure {
            echo 'Pipeline failed!'
            // slackSend message: "Build \${env.BUILD_NUMBER} failed"
        }
        always {
            cleanWs()
        }
    }
}
`
  return {
    filename: 'Jenkinsfile',
    content,
    language: 'groovy',
    generatorType: 'cicd',
    componentLabel: label,
  }
}

// ─────────────────────────────────────────────
// ArgoCD Application Manifest
// ─────────────────────────────────────────────
function generateArgoCDApp(label: string, cfg: Record<string, any>): CICDOutput {
  const appName = label.toLowerCase().replace(/[^a-z0-9-]/g, '-')
  const content = `# Generated by JobStack — ${label}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${appName}
  namespace: ${cfg.appNamespace || 'argocd'}
  labels:
    managed-by: jobstack
spec:
  project: default
  source:
    repoURL: ${cfg.repoUrl || 'https://github.com/org/repo'}
    targetRevision: ${cfg.targetRevision || 'HEAD'}
    path: k8s/
    # Uncomment for Helm:
    # chart: ${appName}
    # helm:
    #   valueFiles:
    #     - values.yaml
    #     - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ${cfg.destinationNamespace || 'default'}
  syncPolicy:
    ${cfg.syncPolicy === 'automated' ? `automated:\n      selfHeal: ${cfg.selfHeal ?? true}\n      prune: ${cfg.prune ?? true}` : 'syncOptions: []'}
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
`
  return {
    filename: 'argocd-app.yaml',
    content,
    language: 'yaml',
    generatorType: 'kubernetes',
    componentLabel: label,
  }
}

// ─────────────────────────────────────────────
// Helm values.yaml
// ─────────────────────────────────────────────
function generateHelmValues(label: string, cfg: Record<string, any>): CICDOutput {
  const content = `# Generated by JobStack — ${label}
# Helm chart values — customize for your environment
replicaCount: ${cfg.replicaCount ?? 1}

image:
  repository: ${cfg.imageRepository || 'my-registry/my-app'}
  pullPolicy: IfNotPresent
  tag: "${cfg.imageTag || 'latest'}"

service:
  type: ${cfg.serviceType || 'ClusterIP'}
  port: 80

ingress:
  enabled: ${cfg.ingressEnabled ?? false}
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  # hosts:
  #   - host: app.example.com
  #     paths: ["/"]

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

env: []
# - name: DATABASE_URL
#   valueFrom:
#     secretKeyRef:
#       name: app-secrets
#       key: database-url
`
  return {
    filename: 'helm/values.yaml',
    content,
    language: 'yaml',
    generatorType: 'kubernetes',
    componentLabel: label,
  }
}

// ─────────────────────────────────────────────
// Prometheus scrape config
// ─────────────────────────────────────────────
function generatePrometheus(label: string, cfg: Record<string, any>): CICDOutput {
  const content = `# Generated by JobStack — ${label}
global:
  scrape_interval: ${cfg.scrapeInterval || '15s'}
  evaluation_interval: ${cfg.evaluationInterval || '15s'}

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

rule_files: []
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${cfg.port || 9090}']

  - job_name: 'application'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Add more scrape targets as needed
`
  return {
    filename: 'prometheus.yml',
    content,
    language: 'yaml',
    generatorType: 'monitoring',
    componentLabel: label,
  }
}

// ─────────────────────────────────────────────
// Datadog agent config
// ─────────────────────────────────────────────
function generateDatadog(label: string, cfg: Record<string, any>): CICDOutput {
  const content = `# Generated by JobStack — ${label}
# Datadog Agent Configuration (datadog.yaml)
# Set DD_API_KEY environment variable — never hardcode API keys!
api_key: "\${DD_API_KEY}"

site: ${cfg.site || 'datadoghq.com'}

env: ${cfg.env || 'production'}
service: ${cfg.service || 'my-app'}

logs_enabled: ${cfg.logsEnabled ?? true}
logs_config:
  container_collect_all: true

apm_config:
  enabled: ${cfg.apmEnabled ?? true}
  env: ${cfg.env || 'production'}

process_config:
  enabled: ${cfg.processAgentEnabled ? '"true"' : '"false"'}

dogstatsd_config:
  enabled: true
  port: 8125

tags:
  - "env:${cfg.env || 'production'}"
  - "service:${cfg.service || 'my-app'}"
  - "managed-by:jobstack"
`
  return {
    filename: 'datadog.yaml',
    content,
    language: 'yaml',
    generatorType: 'monitoring',
    componentLabel: label,
  }
}

// ─────────────────────────────────────────────
// docker-compose service snippet
// ─────────────────────────────────────────────
function generateDockerCompose(id: string, label: string, cfg: Record<string, any>): CICDOutput {
  let serviceBlock: string

  if (id === 'rabbitmq') {
    serviceBlock = `  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${cfg.defaultUser || 'admin'}
      RABBITMQ_DEFAULT_PASS: \${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${cfg.vhost || '/'}
    ports:
      - "${cfg.amqpPort || 5672}:5672"
      - "${cfg.managementPort || 15672}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5`
  } else if (id === 'kafka') {
    serviceBlock = `  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    ports:
      - "${cfg.port || 9092}:9092"
    environment:
      KAFKA_BROKER_ID: ${cfg.brokerId ?? 1}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${cfg.port || 9092}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${cfg.replicationFactor ?? 1}
      KAFKA_LOG_RETENTION_HOURS: ${cfg.retentionHours ?? 168}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"`
  } else if (id === 'nats') {
    serviceBlock = `  nats:
    image: nats:2.10-alpine
    ports:
      - "${cfg.port || 4222}:4222"
      - "${cfg.monitorPort || 8222}:8222"
    command: >
      --jetstream
      --store_dir=/data
    volumes:
      - nats_data:/data`
  } else {
    serviceBlock = `  ${label.toLowerCase().replace(/[^a-z0-9-]/g, '-')}:
    image: # TODO: specify image
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production`
  }

  const volumesBlock = id === 'rabbitmq'
    ? '\nvolumes:\n  rabbitmq_data:'
    : id === 'nats'
    ? '\nvolumes:\n  nats_data:'
    : ''

  const content = `# Generated by JobStack — ${label}
# Add this service to your existing docker-compose.yml
version: '3.9'

services:
${serviceBlock}
${volumesBlock}
`
  return {
    filename: `docker-compose.${id}.yml`,
    content,
    language: 'yaml',
    generatorType: 'docker',
    componentLabel: label,
  }
}

// ─────────────────────────────────────────────
// Main entry point
// ─────────────────────────────────────────────
export function generateCICDConfigs(nodes: Node<NodeData>[], _edges: Edge[]): CICDResult {
  const outputs: CICDOutput[] = []
  const skipped: { label: string; reason: string }[] = []

  nodes.forEach(node => {
    const componentId = node.data?.componentId || node.data?.component
    if (!componentId) return

    const component = getComponentById(componentId)
    if (!component) return

    const genType = getEffectiveGeneratorType(component)
    if (genType === 'terraform') return // handled by terraform generator

    const label = String(node.data?.label || component.name)
    const cfg: Record<string, any> = {
      ...(component.cicd?.defaultConfig || {}),
      ...(node.data?.config || {}),
    }

    switch (componentId) {
      case 'github-actions':
        outputs.push(generateGitHubActions(label, cfg))
        break
      case 'gitlab-ci':
        outputs.push(generateGitLabCI(label, cfg))
        break
      case 'jenkins':
        outputs.push(generateJenkinsfile(label, cfg))
        break
      case 'argocd':
        outputs.push(generateArgoCDApp(label, cfg))
        break
      case 'helm':
        outputs.push(generateHelmValues(label, cfg))
        break
      case 'prometheus':
        outputs.push(generatePrometheus(label, cfg))
        break
      case 'datadog':
        outputs.push(generateDatadog(label, cfg))
        break
      case 'rabbitmq':
      case 'kafka':
      case 'nats':
      case 'docker':
        outputs.push(generateDockerCompose(componentId, label, cfg))
        break
      case 'documentation':
      case 'vault':
      case 'ansible':
      case 'terraform':
        skipped.push({ label, reason: 'Annotation-only component — used for architectural documentation only, no code generated' })
        break
      default:
        if (genType === 'documentation') {
          skipped.push({ label, reason: 'No code generator for this component type — used as architectural annotation' })
        } else if (genType === 'monitoring') {
          skipped.push({ label, reason: `Monitoring config for "${component.name}" — open the Output tab in the config panel to preview` })
        } else {
          skipped.push({ label, reason: `Generator type "${genType}" not yet implemented for ${component.name}` })
        }
    }
  })

  return { outputs, skipped }
}

/** Get only the nodes that a CI/CD generator can handle */
export function getCICDNodes(nodes: Node<NodeData>[]): Node<NodeData>[] {
  return nodes.filter(node => {
    const id = node.data?.componentId || node.data?.component
    if (!id) return false
    const component = getComponentById(id)
    if (!component) return false
    const genType = getEffectiveGeneratorType(component)
    return genType !== 'terraform' && genType !== 'documentation'
  })
}
