'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Code2, GitBranch, Building2, Github, Check } from 'lucide-react'

// ─────────────────────────────────────────────────────────────────────────────
// Types & data
// ─────────────────────────────────────────────────────────────────────────────

type TabId = 'iaas' | 'cicd' | 'governance' | 'github'

interface TabDef {
  id: TabId
  icon: React.ReactNode
  label: string
  badgeColor: string
  badge: string
  title: string
  desc: string
  bullets: string[]
  fileName: string
  lang: 'hcl' | 'yaml'
  code: string[]
}

const TABS: TabDef[] = [
  {
    id: 'iaas',
    icon: <Code2 className="h-4 w-4" />,
    label: 'IaaS Generation',
    badge: 'HCL',
    badgeColor: 'bg-violet-500/10 text-violet-400 border-violet-500/20',
    title: 'Terraform from your diagram',
    desc: 'Drop nodes onto the canvas — JobStack writes production-ready HCL. Every edge becomes a resource association.',
    bullets: [
      'VNet, Subnet, NSG, and associations auto-generated',
      'Load balancer backend pool wiring from edge semantics',
      'Variable blocks with sensible defaults for every SKU',
      'Remote state backend block included out of the box',
    ],
    fileName: 'resources.tf',
    lang: 'hcl',
    code: [
      '# Generated by JobStack — resources.tf',
      'resource "azurerm_virtual_network" "prod_vnet" {',
      '  name                = "${var.project_name}-vnet"',
      '  address_space       = ["10.0.0.0/16"]',
      '  location            = var.azure_location',
      '  resource_group_name = azurerm_resource_group.rg.name',
      '}',
      '',
      '# NSG attachment — from edge: Web Subnet → NSG',
      'resource "azurerm_subnet_network_security_group_association" "nsg_assoc_prod_nsg" {',
      '  subnet_id                 = azurerm_subnet.web_subnet.id',
      '  network_security_group_id = azurerm_network_security_group.prod_nsg.id',
      '}',
      '',
      '# LB Backend Pool — from edge: LB → VM',
      'resource "azurerm_lb_backend_address_pool" "pool_prod_lb" {',
      '  loadbalancer_id = azurerm_lb.prod_lb.id',
      '  name            = "BackendPool"',
      '}',
      '',
      'resource "azurerm_network_interface_backend_address_pool_association" "bap_nic_web_vm" {',
      '  network_interface_id    = azurerm_network_interface.nic_web_vm.id',
      '  ip_configuration_name   = "internal"',
      '  backend_address_pool_id = azurerm_lb_backend_address_pool.pool_prod_lb.id',
      '}',
    ],
  },
  {
    id: 'cicd',
    icon: <GitBranch className="h-4 w-4" />,
    label: 'CI/CD Pipelines',
    badge: 'YAML',
    badgeColor: 'bg-sky-500/10 text-sky-400 border-sky-500/20',
    title: 'Pipelines that deploy your diagram',
    desc: 'Each architecture gets a GitHub Actions workflow. Plan on PR, apply on merge — no manual wiring.',
    bullets: [
      'Terraform init / plan / apply steps auto-populated',
      'Azure ARM credentials injected from GitHub Secrets',
      'PR comment with plan output via actions/github-script',
      'Environment protection rules for production gates',
    ],
    fileName: '.github/workflows/deploy.yml',
    lang: 'yaml',
    code: [
      '# Generated by JobStack — deploy.yml',
      'name: Deploy to Azure',
      '',
      'on:',
      '  push:',
      '    branches: [main]',
      '  pull_request:',
      '    branches: [main]',
      '',
      'jobs:',
      '  terraform:',
      '    runs-on: ubuntu-latest',
      '    environment: production',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '',
      '      - name: Azure Login',
      '        uses: azure/login@v2',
      '        with:',
      '          client-id: ${{ secrets.AZURE_CLIENT_ID }}',
      '          tenant-id: ${{ secrets.AZURE_TENANT_ID }}',
      '          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}',
      '',
      '      - name: Terraform Plan',
      '        run: |',
      '          terraform init',
      '          terraform plan -out=tfplan',
      '',
      '      - name: Terraform Apply',
      '        if: github.ref == \'refs/heads/main\'',
      '        run: terraform apply tfplan',
    ],
  },
  {
    id: 'governance',
    icon: <Building2 className="h-4 w-4" />,
    label: 'Cloud Governance',
    badge: 'HCL',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    title: 'Management Groups as code',
    desc: 'Model your organisation\'s Management Group hierarchy visually. Get HCL for policy, RBAC, and subscription placement.',
    bullets: [
      'Management Group hierarchy with nested child groups',
      'Subscription-to-group association resources',
      'Role assignment blocks for each principal on every scope',
      'Policy definition + initiative assignment scaffolding',
    ],
    fileName: 'governance.tf',
    lang: 'hcl',
    code: [
      '# Generated by JobStack — governance.tf',
      'resource "azurerm_management_group" "root" {',
      '  display_name = "Contoso Root"',
      '}',
      '',
      'resource "azurerm_management_group" "platform" {',
      '  display_name               = "Platform"',
      '  parent_management_group_id = azurerm_management_group.root.id',
      '}',
      '',
      'resource "azurerm_management_group" "workloads" {',
      '  display_name               = "Workloads"',
      '  parent_management_group_id = azurerm_management_group.root.id',
      '}',
      '',
      '# Subscription placement — drag-to-group edge',
      'resource "azurerm_management_group_subscription_association" "prod" {',
      '  management_group_id = azurerm_management_group.workloads.id',
      '  subscription_id     = "/subscriptions/${var.prod_subscription_id}"',
      '}',
      '',
      '# RBAC — Contributor on Workloads scope',
      'resource "azurerm_role_assignment" "platform_contributor" {',
      '  scope                = azurerm_management_group.workloads.id',
      '  role_definition_name = "Contributor"',
      '  principal_id         = var.platform_team_group_object_id',
      '}',
    ],
  },
  {
    id: 'github',
    icon: <Github className="h-4 w-4" />,
    label: 'GitHub Integration',
    badge: 'YAML',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    title: 'PR comments with Terraform Plan',
    desc: 'JobStack-generated pipelines post the plan diff directly to your pull request. Review infra changes like code.',
    bullets: [
      'Inline plan output posted as PR comment',
      'Links back to the JobStack diagram version',
      'Fails the check if plan contains destroys on protected resources',
      'Auto-updates comment on each new push — no spam',
    ],
    fileName: '.github/workflows/pr-plan.yml',
    lang: 'yaml',
    code: [
      '# Generated by JobStack — pr-plan.yml',
      'name: Terraform PR Plan',
      '',
      'on:',
      '  pull_request:',
      '    paths: [\'**.tf\']',
      '',
      'jobs:',
      '  plan:',
      '    runs-on: ubuntu-latest',
      '    permissions:',
      '      pull-requests: write',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '',
      '      - name: Terraform Plan',
      '        id: plan',
      '        run: terraform plan -no-color 2>&1 | tee plan.txt',
      '',
      '      - name: Comment Plan on PR',
      '        uses: actions/github-script@v7',
      '        with:',
      '          script: |',
      '            const plan = require(\'fs\').readFileSync(\'plan.txt\', \'utf8\')',
      '            github.rest.issues.createComment({',
      '              issue_number: context.issue.number,',
      '              owner: context.repo.owner,',
      '              repo: context.repo.repo,',
      '              body: `## Terraform Plan\\n\`\`\`\\n${plan}\\n\`\`\``,',
      '            })',
    ],
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Inline syntax highlighter
// ─────────────────────────────────────────────────────────────────────────────

function highlightHCL(line: string) {
  if (!line.trim()) return <span>&nbsp;</span>

  // Comment
  if (line.trimStart().startsWith('#')) {
    return <span className="text-zinc-600">{line}</span>
  }

  // resource / data / variable / output keywords
  const kwMatch = line.match(/^(\s*)(resource|data|variable|output|locals|module|provider)\b(.*)$/)
  if (kwMatch) {
    return (
      <>
        <span>{kwMatch[1]}</span>
        <span className="text-violet-400">{kwMatch[2]}</span>
        <span className="text-emerald-300">{kwMatch[3]}</span>
      </>
    )
  }

  // Key = "string"
  const strMatch = line.match(/^(\s*)(\w+)\s*(=)\s*(".*")(.*)$/)
  if (strMatch) {
    return (
      <>
        <span>{strMatch[1]}</span>
        <span className="text-sky-300">{strMatch[2]}</span>
        <span className="text-zinc-500">{' = '}</span>
        <span className="text-emerald-300">{strMatch[4]}</span>
        <span className="text-zinc-400">{strMatch[5]}</span>
      </>
    )
  }

  // Key = value (non-string)
  const valMatch = line.match(/^(\s*)(\w+)\s*(=)\s*(.+)$/)
  if (valMatch) {
    return (
      <>
        <span>{valMatch[1]}</span>
        <span className="text-sky-300">{valMatch[2]}</span>
        <span className="text-zinc-500">{' = '}</span>
        <span className="text-amber-300">{valMatch[4]}</span>
      </>
    )
  }

  // Brackets
  if (line.trim() === '}' || line.trim() === '{') {
    return <span className="text-zinc-600">{line}</span>
  }

  return <span className="text-zinc-300">{line}</span>
}

function highlightYAML(line: string) {
  if (!line.trim()) return <span>&nbsp;</span>

  // Comment
  if (line.trimStart().startsWith('#')) {
    return <span className="text-zinc-600">{line}</span>
  }

  // List item
  const listMatch = line.match(/^(\s*-\s+)(.*)$/)
  if (listMatch) {
    return (
      <>
        <span className="text-amber-400">{listMatch[1]}</span>
        <span className="text-zinc-300">{listMatch[2]}</span>
      </>
    )
  }

  // key: "value" / key: value
  const kvMatch = line.match(/^(\s*)([\w-]+)(\s*:\s*)(.*)$/)
  if (kvMatch) {
    const val = kvMatch[4]
    const valEl = val.startsWith("'") || val.startsWith('"')
      ? <span className="text-emerald-300">{val}</span>
      : <span className="text-sky-300">{val}</span>
    return (
      <>
        <span>{kvMatch[1]}</span>
        <span className="text-violet-400">{kvMatch[2]}</span>
        <span className="text-zinc-500">{kvMatch[3]}</span>
        {valEl}
      </>
    )
  }

  return <span className="text-zinc-300">{line}</span>
}

function CodeLine({ line, lang }: { line: string; lang: 'hcl' | 'yaml' }) {
  return (
    <div className="px-4 leading-[1.65] hover:bg-white/[0.02] transition-colors">
      {lang === 'hcl' ? highlightHCL(line) : highlightYAML(line)}
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────────────────────

export function FeatureTabs() {
  const [active, setActive] = useState<TabId>('iaas')
  const tab = TABS.find(t => t.id === active)!

  return (
    <div className="rounded-2xl border border-border/50 bg-card overflow-hidden shadow-xl">
      <div className="grid lg:grid-cols-[220px_1fr]">
        {/* ── left sidebar – vertical tabs ── */}
        <div className="bg-muted/30 border-b lg:border-b-0 lg:border-r border-border/40 flex lg:flex-col">
          {TABS.map(t => (
            <button
              key={t.id}
              onClick={() => setActive(t.id)}
              className={[
                'flex items-center gap-2.5 px-4 py-3.5 text-xs font-medium border-b lg:border-b lg:last:border-b-0 border-border/30 transition-all text-left relative',
                active === t.id
                  ? 'text-foreground bg-background/60'
                  : 'text-muted-foreground hover:text-foreground hover:bg-background/30',
              ].join(' ')}
            >
              {active === t.id && (
                <motion.div
                  layoutId="tab-indicator"
                  className="absolute left-0 top-0 bottom-0 w-[3px] bg-primary rounded-r-full"
                  transition={{ type: 'spring', stiffness: 400, damping: 32 }}
                />
              )}
              {t.icon}
              {t.label}
            </button>
          ))}
        </div>

        {/* ── right panel ── */}
        <AnimatePresence mode="wait">
          <motion.div
            key={active}
            initial={{ opacity: 0, x: 10 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -10 }}
            transition={{ duration: 0.22 }}
            className="grid md:grid-cols-[1fr_1.3fr] min-h-[340px]"
          >
            {/* description */}
            <div className="p-6 border-b md:border-b-0 md:border-r border-border/40 flex flex-col gap-4 justify-center">
              <span className={`inline-flex w-fit text-[10px] px-2 py-0.5 rounded border font-mono font-bold ${tab.badgeColor}`}>
                {tab.badge}
              </span>
              <div>
                <h3 className="text-sm font-semibold mb-1.5">{tab.title}</h3>
                <p className="text-xs text-muted-foreground leading-relaxed">{tab.desc}</p>
              </div>
              <ul className="space-y-2">
                {tab.bullets.map((b, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                    <Check className="h-3.5 w-3.5 text-primary mt-px shrink-0" />
                    {b}
                  </li>
                ))}
              </ul>
            </div>

            {/* code preview */}
            <div className="bg-zinc-950 flex flex-col overflow-hidden">
              {/* file bar */}
              <div className="flex items-center gap-2 px-4 py-2 border-b border-zinc-800">
                <div className="flex gap-1 mr-1">
                  <div className="w-2.5 h-2.5 rounded-full bg-rose-500/60" />
                  <div className="w-2.5 h-2.5 rounded-full bg-amber-500/60" />
                  <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/60" />
                </div>
                <span className="text-[10px] text-zinc-500 font-mono">{tab.fileName}</span>
                <span className={`ml-auto text-[9px] px-1.5 py-0.5 rounded border font-mono ${tab.badgeColor}`}>
                  {tab.badge}
                </span>
              </div>

              {/* code body */}
              <div className="flex overflow-auto flex-1 font-mono text-[10.5px] leading-none py-3">
                {/* line numbers */}
                <div className="text-zinc-700 text-right pr-4 pl-3 select-none shrink-0">
                  {tab.code.map((_, i) => (
                    <div key={i} className="leading-[1.65]">{i + 1}</div>
                  ))}
                </div>
                {/* code */}
                <div className="flex-1 pr-4">
                  {tab.code.map((line, i) => (
                    <CodeLine key={i} line={line} lang={tab.lang} />
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  )
}
